![toporpa.png]()

# 💻 MÓDULO 01 | INTRO: LINGUAGEM DE PROGRAMAÇÃO PYTHON | PARTE 03
---  

> *Este material foi revisado e estruturado didaticamente para a capacitação Jornada RPA da DB Assessoria em Sistemas de Informação.
O objetivo geral é guiar a introdução na (ou revisão da) Linguagem de Programação Python para que possamos seguir compreender exemplos e construir práticas de automação robótica de processos.*
>
&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Este é a PARTE 3 que irá cobrir os seguintes conteúdos:**

- INTERAÇÃO COM ARQUIVOS: interação com diferentes tipos de arquivos, arquivos texto, arquivos em formato CSV e em formato JSON.

- MANIPULAÇÃO DE DADOS: manipulação de dados com biblioteca Pandas.

## 📄 ARQUIVOS DE TEXTO
------

Existem diferentes modos de abertura de arquivos:

"r" - read: é o valor padrão, abre o arquivo para leitura e apresenta erro se o arquivo não existir.

"a" - append - abre o arquivo para adicionar conteúdo e cria um novo se o arquivo não existir.

"w" - write - abre o arquivo para escrita, sobrescreve se o arquivo já existir e criar um novo se o arquivo não existir.

"x" - create - cria um arquivo específico e retorna um erro caso o arquivo já existir.

Podemos também definir se estamos lidando com um arquivo de texto ou arquivo binário.

"t" - text: é o valor padrão, modo de texto.

"b" - binary: modo binário, por exemplo: images, arquivos PDF e etc.

In [ ]:
with open("arquivo.txt", "w") as arq:
    arq.write("Estamos escrevendo a primeira linha do arquivo\n")
    arq.write("Vejam só, esta é a segunda linha do arquivo\n")
    arq.close()

In [ ]:
arq = open("arquivo.txt", "r")

# leitura de uma linha do arquivo
# print(arq.readline())

# leitura de todas as linhas do arquivo e coloca em uma lista
print(arq.readlines())
arq.close()

['Estamos escrevendo a primeira linha do arquivo\n', 'Vejam só, esta é a segunda linha do arquivo\n', 'Este é um terceiro conteúdo\n', 'Este é o quarto conteúdo\n']

In [ ]:
with open("arquivo.txt", "a") as arq:
    arq.writelines(["Este é um terceiro conteúdo\n", "Este é o quarto conteúdo\n"])

In [ ]:
print("Nome: " + arq.name)
print("Modo: " + arq.mode)
print("Tipo: " + str(type(arq)))

Nome: arquivo.txt
Modo: r
Tipo: <class '_io.TextIOWrapper'>

In [ ]:
arq = open("arquivo.txt", "r")
# indica o ponto onde o cursor de movimentação do arquivo se encontra
print("Está em: %s" % arq.tell())
print(arq.readlines())
print("Está em: %s" % arq.tell())
arq.seek(0)
print("Está em: %s" % arq.tell())

Está em: 0
['Estamos escrevendo a primeira linha do arquivo\n', 'Vejam só, esta é a segunda linha do arquivo\n', 'Este é um terceiro conteúdo\n', 'Este é o quarto conteúdo\n']
Está em: 150
Está em: 0

In [ ]:
with open("arquivo.txt", "r") as arq:
    # delimita a quantidade de caracteres a serem lidos
    print(arq.read(4))
    print(arq.tell())
    print(arq.read(6))

Esta
4
mos es

In [ ]:
with open("arquivo.txt", "r") as arq:
    linhas = arq.readlines()
    for linha in linhas:
        print(linha)

Estamos escrevendo a primeira linha do arquivo

Vejam só, esta é a segunda linha do arquivo

Este é um terceiro conteúdo

Este é o quarto conteúdo

## 🗃️ ARQUIVOS CSV
-------

In [ ]:
import csv

arqcsv = "filmes.csv"
lista = []

with open(arqcsv, "r") as arq:
    formato_csv = csv.reader(arq)
    for linha in formato_csv:
        lista.append(linha)
    #for linha in formato_csv:
    #   print(linha[0])
    # acessando a linha 100 do arquivo, mas terceiro elemento (gêneros)
    # print(lista[100][2])

0

In [ ]:
print(lista)

[['id', 'titulo', 'generos'], ['1', 'Toy Story (1995)', 'Adventure|Animation|Children|Comedy|Fantasy'], ['2', 'Jumanji (1995)', 'Adventure|Children|Fantasy'], ['3', 'Grumpier Old Men (1995)', 'Comedy|Romance'], ['4', 'Waiting to Exhale (1995)', 'Comedy|Drama|Romance'], ['5', 'Father of the Bride Part II (1995)', 'Comedy'], ['6', 'Heat (1995)', 'Action|Crime|Thriller'], ['7', 'Sabrina (1995)', 'Comedy|Romance'], ['8', 'Tom and Huck (1995)', 'Adventure|Children'], ['9', 'Sudden Death (1995)', 'Action'], ['10', 'GoldenEye (1995)', 'Action|Adventure|Thriller'], ['11', 'American President, The (1995)', 'Comedy|Drama|Romance'], ['12', 'Dracula: Dead and Loving It (1995)', 'Comedy|Horror'], ['13', 'Balto (1995)', 'Adventure|Animation|Children'], ['14', 'Nixon (1995)', 'Drama'], ['15', 'Cutthroat Island (1995)', 'Action|Adventure|Romance'], ['16', 'Casino (1995)', 'Crime|Drama'], ['17', 'Sense and Sensibility (1995)', 'Drama|Romance'], ['18', 'Four Rooms (1995)', 'Comedy'], ['19', 'Ace Ventura: When Nature Calls (1995)', 'Comedy']...

In [ ]:
with open("novo_arquivo.csv", "w") as arq_novo:
    novo = csv.writer(arq_novo, delimiter="\t")
    novo.writerows(lista)

In [ ]:
# Descobrir o delimitador do arquivo em formato CSV

with open("novo_arquivo.csv", "r") as arq_novo:
#with open("filmes.csv", "r") as arq_novo:
    dialect = csv.Sniffer().sniff(arq_novo.read(1024))
    print("* " + dialect.delimiter + " *")

* 	 *

## 💡 ARQUIVOS JSON
----

Importação do arquivo JSON para List

In [ ]:
import json

with open("filmes.json", "r") as arq_json:
    dados = json.load(arq_json)
    print(dados)

for linha in dados:
    print(linha["titulo"])

FileNotFoundError: ignored

# 🐼 &nbsp; BIBLIOTECA PANDAS
---

### 📢&nbsp;&nbsp;INTRODUÇÃO

A biblioteca [Pandas](https://pandas.pydata.org/) é amplamente utilizada para se trabalhar com grandes datasets em análise de dados e tem como base a Linguagem de Programação Python. Apresenta funcionalidades de análise, pré-processamento, exploração e manipulação dse dados. O nome "Pandas" vem de "Panel Data" e "Python Data Analysis" e foi criado por Wes McKinney em 2008.

Tem uma ótima performance no trabalho com dados usando o objeto DataFrame que se trata de uma estrutura de dados tabular, orientada a colunas, com rótulos (labels) tanto para linhas quanto para colunas e também com arrays unidimensionais chamados com o objeto Series.

Usando o processamento de alto desempenho de arrays da biblioteca [NumPy](https://numpy.org/) com recursos bastantes flexíveis para manipulação de dados tanto de planilhas, quanto em banco de dados relacionais. A biblioteca permite analisar grandes quantidades de dados e gerar conclusões baseadas em teorias estatísticas. Além disso pode realizar um ótimo apoio nas tarefas de pré-processamento dos dados, tais como a detecção de valores faltantes, substituição de valores e etc, tornando mais legíveis e relevantes. Além disso,
podemos trabalhar com processos estatísticos como contagem, média, mediana, moda, valor máximo, valor mínimo, além de correlações.

Para a referência completa da biblioteca Pandas acesse a [documentação oficial](http://pandas.pydata.org/pandas-docs/stable/index.html).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Este material didático irá cobrir os seguintes conteúdos:**
  * Estruturas de dados em `DataFrame` e `Series` da biblioteca *Pandas*
  * Acesso e manipulação de dados com `DataFrame` e `Series`
  * Importação de dados de arquivo CSV e manipulação através de `DataFrame`

####Importação e utilização

Para importar a biblioteca Pandas basta chama-la usando a palavra chave `import`.

É recomendável criar um `alias` para chamada da biblioteca, como no exeplo a seguir, estamos nomeando o acesso como `pd`

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
import pandas as pd

Caso você precise saber qual a versão do Pandas está instalada atualmente, use o comando a seguir:

In [ ]:
pd.__version__

'1.5.3'

Para exibir de uma maneira mais legível os dados dos DataFrames, vamos importar também o módulo `display` da biblioteca `IPython`.

In [ ]:
from IPython.display import display

### 🎲&nbsp;&nbsp;ESTRUTURAS DE DADOS

As estruturas de dados primárias no Pandas são implementadas em duas classes:

* **`DataFrame`**: uma estrutura tal qual uma tabela relacional com linhas e colunas.
* **`Series`**: que contém uma única coluna

Assim, um `DataFrame` contém uma ou mais `Series` e um nome para cada `Series`.

A estrutura de DataFrame é bastante comum na abstração para manipulação de dados e também é implementada em no framework [Spark](https://spark.apache.org/) e na Linguagem [R](https://www.r-project.org/about.html).

Objetos `DataFrame` podem ser criados passando um dicionários mapeando os nomes das colunas para suas respectivas `Series`. Se a `Series` não coincide no tamanho, valores faltantes são preenchidos com [NA/NaN](http://pandas.pydata.org/pandas-docs/stable/missing_data.html).

#### Séries

Séries não estruturas unidimensionais que podem ter índices numéricos ou em outros formatos.

Podemos usar a estrutura de dados `Series` passando os valores em uma lista.
O segundo parâmetro `index` indica qual deve ser o identificar de índice para cada elemento. Caso não seja designados valores para o índice, os valores serão números em ordem crescente iniciando por 0.

\

In [ ]:
s = pd.Series(["Azul", "Roxo", "Laranja"], index=[0, 2, 4])
display(s)

0       Azul
2       Roxo
4    Laranja
dtype: object

Para saber a quantidade de valores em uma série usa-se `size`:

In [ ]:
s.size

3

Para retornar um array com os valores contidos na série, usa-se `values`:

In [ ]:
s.values

array(['Azul', 'Roxo', 'Laranja'], dtype=object)

Podemos acessar um valor diretamente pelo seu índice com `at`:

In [ ]:
s[2]

'Roxo'

Estrutura para buscar todos `findall`

In [ ]:
s.str.findall("Roxo")

0        []
2    [Roxo]
4        []
dtype: object

Para exibição da lista, podemos adicionar elementos depois com `add()` e antes com `radd()`. Esses elementos são apenas para visualização.

In [ ]:
s.add("!").radd("#")

0       #Azul!
2       #Roxo!
4    #Laranja!
dtype: object

Para adicionar novos valores em uma série o recomendado é utilizar a função do pandas `concat`. Ela aceita apenas a concatenação de uma série em outra, portanto deve-se passar como primeiro parâmetro a série atual e como segundo parâmetro a nova série a ser agregada.

In [ ]:
s = pd.concat([s, pd.Series(["Amarelo", "Verde"], index=[6, 8])])

In [ ]:
display(s)

0       Azul
2       Roxo
4    Laranja
6    Amarelo
8      Verde
dtype: object

Se não estipularmos os valores de índice, podemos passar como terceiro  parâmetro `ignore_index=True` para que seja estruturada a indexação adequadamente.

In [ ]:
s1 = pd.Series(["Uva", "Maça", "Morango"])
display(s1)

s2 = pd.Series(["Banana", "Morango"])
display(s2)

sn = pd.concat([s1, s2], ignore_index=True)
display(sn)

0        Uva
1       Maça
2    Morango
dtype: object

0     Banana
1    Morango
dtype: object

0        Uva
1       Maça
2    Morango
3     Banana
4    Morango
dtype: object

Ao usar `is_unique` avalia se os valores todos são únicos. Neste caso irá retornar `False`, pois temos o valor "morango" repetido.

In [ ]:
sn.is_unique

False

Para retornar em um array apenas os valores únicos, pode-se usar `unique()`

In [ ]:
sn.unique()

array(['Uva', 'Maça', 'Morango', 'Banana'], dtype=object)

Podemos reindexar os índices caso seja necessário. Na série `s` temos atualmente os índices 0, 2, 4, 6 e 8, se quisermos reindexar para que a série tenha 10 valores, teremos que definnir quais são os valores faltantes.

Assim, existem opções para o método de completude de dados:
`ffill`: último valor válido;
`bfill`: próximo valor válido;
`nearest`: o valor mais próximos;  

Ainda, pode-se estabelecer um valor usando `fill_value` (por exemplo: `fill_value="VAZIO"`)

In [ ]:
s.reindex(range(10), method="nearest") # fill_value="NULL"

0       Azul
1       Roxo
2       Roxo
3    Laranja
4    Laranja
5    Amarelo
6    Amarelo
7      Verde
8      Verde
9      Verde
dtype: object

#### DataFrame

Um DataFrame é um objeto que representa uma tabela e contém uma coleção ordenada de colunas em que cada uma pode ter um tipo de valor diferente. Possui um índice tanto para linha quanto para coluna, podendo ser imaginado como um dicionário de séries onde todos compartilham o mesmo índice (MCKINNEY, 2018, p. 117).

Para criar um dataframe devemos usar a função `DataFrame` da biblioteca Pandas, passando como parâmetro um dicionário de dados.

In [ ]:
df = pd.DataFrame({"nome": ["Aline", "Pedro", "Marina", "José"],
                   "idade": [39, 35, 28, 45],
                   "pet": ["gato", "cachorro", "papagaio", "peixe"]})

In [ ]:
display(df)

     nome  idade       pet
0   Aline     39      gato
1   Pedro     35  cachorro
2  Marina     28  papagaio
3    José     45     peixe

Para exibir as colunas de um DataFrame usa-se `columns`:

In [ ]:
df.columns

Index(['nome', 'idade', 'pet'], dtype='object')

Já para exibir valores de um DataFrame usa-se `values`:

In [ ]:
df.values

array([['Aline', 39, 'gato'],
       ['Pedro', 35, 'cachorro'],
       ['Marina', 28, 'papagaio'],
       ['José', 45, 'peixe']], dtype=object)

Criando um nome para a estrutura de índices do DataFrame com `index.name`:

In [ ]:
df.index.name = "id"
display(df)

      nome  idade       pet
id
0    Aline     39      gato
1    Pedro     35  cachorro
2   Marina     28  papagaio
3     José     45     peixe

Para inserção de um novo valor no DataFrame, devemos usar a função da biblioteca Pandas `concat` passando como parâmetro outro DataFrame a ser concatenado.

In [ ]:
dados = pd.DataFrame({ "nome": ["Abelino"],
                       "idade":[67],
                       "pet": ["cachorro"] })
pd.concat([df, dados], ignore_index=True)

      nome  idade       pet
0    Aline     39      gato
1    Pedro     35  cachorro
2   Marina     28  papagaio
3     José     45     peixe
4  Abelino     67  cachorro

Caso seja necessário realizar a transposição de um DataFrame (as linhas tornam-se colunas e vice-versa) usa-se `T` associado ao DataFrame. Perceba que a transposição é feita apenas em tempo de execução, para usar a estrutura transporta é preciso associar a um novo DataFrame.

In [ ]:
df.T

id         0         1         2      3
nome   Aline     Pedro    Marina   José
idade     39        35        28     45
pet     gato  cachorro  papagaio  peixe

Uma forma interessante de visualização de um DataFrame é o oferecido pela função `stack()`. Ele apresenta a estrutura em um formato presenta multinível.

In [ ]:
df.stack()

id
0   nome        Aline
    idade          39
    pet          gato
1   nome        Pedro
    idade          35
    pet      cachorro
2   nome       Marina
    idade          28
    pet      papagaio
3   nome         José
    idade          45
    pet         peixe
dtype: object

Se for necessário inserir uma nova coluna no DataFrame, podemos usar a função `insert()`. Passamos por parâmetro a posição onde a coluna deverá ser inserida, o nome da coluna (label) e o valor padrão a ser inserido.

In [ ]:
df.insert(3, "status", "ativo")

In [ ]:
df

      nome  idade       pet status
id
0    Aline     39      gato  ativo
1    Pedro     35  cachorro  ativo
2   Marina     28  papagaio  ativo
3     José     45     peixe  ativo

Para retirar uma coluna, usa-se `drop()` passando por parâmetro o nome da coluna.

In [ ]:
df.drop("status", axis="columns")

      nome  idade       pet
id
0    Aline     39      gato
1    Pedro     35  cachorro
2   Marina     28  papagaio
3     José     45     peixe

Caso seja necessário verificar se determinado valor de índica existe, devemos usar `in` buscando na lista de índices `index`:

In [ ]:
6 in df.index

False

### 🧩&nbsp;&nbsp;MANIPULAÇÃO DE DADOS

#### Lendo um arquivo csv

Na maioria das vezes que vamos trabalhar com a biblioteca Pandas a nossa necessidade será realizar a leitura e manipulação de um conjunto de dados que esteja em um arquivo, banco de dados, API ou qualquer outra fonte externa.

Assim, podemos ler fontes de dados em diferentes formatos e para isso o Pandas oferece uma conjunto de funções.

|Função | Descrição
|:---:|:---|
| read_csv() | leitura de dados deliminados no formato CSV - Comma Separated Values (padrão: vírgula)
| read_table() | leitura de dados delimitados utilizando tabulação ('\t')
| read_fwf() | leitura de dados delimitados com tamanho fixo de colunas
| read_clipboard() | leitura de dados da área de transferência
| read_excel() | leitura de dados tabulares de arquivos Microsoft Excel
| read_hdf() | leitura de arquivos HDF escritos com o Pandas
| read_html() | leitura de tabelas que se encontram em documentos HTML
| read_json() | leitura de dados na representação JSON - Javascript Object Notation
| read_msgpack() | leitura de dados codificados pelo Pandas no formato binário MessagePack
| read_pickle() | leitura de objeto armazenado no formato pickle do Python
| read_sas() | leitura de dados de SAS armazenado em um fos formatos personalizados do sistema SAS
| read_sql() | leitura do resultado de uma consulta SQL (usando SQLAlchemy) na forma de um DataFrame do Pandas
| read_stata() | leitura de dados no formato de arquivo Stata
| read_feather() | leitura de dados no formato de arquivo binário Feather

Certamente uma das mais populares das funções listadas acima é a read_csv() uma vez que o formato Comma Separated Values (CSV) é bastante utilizado para distribuição de datasets.

A seguir a forma simples de leitura de um dataset passando uma URL. Este dataset foi baixado do [repositório de dados abertos da plataforma AirBnb](http://insideairbnb.com/get-the-data) e corresponde a um recorte de dados da plataforma para o Rio de Janeiro.

In [ ]:
df = pd.read_csv("https://alinedecampos.pro.br/etc/datasets/airbnb.csv")

Além do parâmetro obrigatório que indica o caminho de acesso ao arquivo, temos algumas opções de parâmetros opcionais para tratar questões de interpretação dos dados.

|Função | Descrição
|:---:|:---|
| nrows | número de linhas a serem lidas a partir do início do arquivo
| header | indica o número da linha que contém o cabeçalho (se não houver, deve ser 'None' e o valor padrão é 0)
| sep | apresenta o(s) caracter(es) de separação dos valores
| enconding | indica a codificação de texto (indicado UTF-8)
| thousands | indica o separador de milhares (por exemplo '.'ou ',')
| na_values | indica por qual valor as colunas NA devem ser substituídas
| comment | indica o caracter usado para separar comentários
| skiprows | indica o número das linhaas a serem ignoradas (começando de 0)
| skip_footer | indica o número de linhas a serem ignoradas no final do arquivo
| verbose | exibe várias informações de saída do parser, como o número de valores ausentes em colunas não numéricas
| parse_dates | tenta fazer o parse de dados para DateTime (padrão False)
| dayfirst | trata datas como em formato internacional (padrão False)
| date_parser | função usada para parse de datas
| iterator | devolve um objeto TextParser para ler o arquivo aos poucos
| chunksize | para iteração é o tamanho das partes do arquivo
| squeeze | se os dados contem apenas uma coluna devolve uma série
| index_col | números ou nomes de coluna a serem usados como índice de linhas no resultado
| converters | dicionário contendo o número ou o nome de colunas mapeadas para funções

No exemplo a seguir, vamos ler apenas os primeiros 20 registros do arquivo CSV:

In [ ]:
df20 = pd.read_csv("https://alinedecampos.pro.br/etc/datasets/airbnb.csv", nrows=20)
df20

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,17878,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",68997,Matthias,NaN,Copacabana,-22.96599,-43.17940,Entire home/apt,350,5,272,2022-04-23,1.87,1,311,8,NaN
1,556930647599893392,Venha passar uma pernoite em um veleiro na Urca!,198206849,Andréia,NaN,Urca,-22.94781,-43.16351,Private room,280,1,1,2022-02-19,0.25,1,365,1,NaN
2,1174007,100% Best View In Copa In Suite 2,3962758,Thiago Luiz,NaN,Copacabana,-22.97277,-43.17966,Private room,107,2,177,2022-06-07,1.69,6,357,29,NaN
3,8410797,Ipanema(Arpoador) 100mdo Mar/ Jan & Carnaval +Fev,42038091,Sheila,NaN,Ipanema,-22.98871,-43.19334,Private room,1000,3,1,2017-09-28,0.02,3,362,0,NaN
4,28053241,Navegar a Bordo de um Veleiro Francês no Rio!,193860988,Luciano,NaN,Urca,-22.95056,-43.17175,Private room,1850,2,0,NaN,NaN,1,180,0,NaN
5,249616,Flat at Barra Near by WINDSOR HOTEL,1307761,Malí,NaN,Barra da Tijuca,-23.01097,-43.32266,Entire home/apt,195,3,220,2020-04-20,1.73,2,24,0,NaN
6,249842,"Copacabana, central e perto da praia",1309444,Sonia,NaN,Copacabana,-22.96794,-43.18969,Private room,90,2,140,2022-04-08,1.12,3,6,14,NaN
7,24480,"Nice and cozy near Ipanema Beach, w/ home office",99249,Goya,NaN,Ipanema,-22.98405,-43.20189,Entire home/apt,671,3,85,2018-02-14,0.59,1,281,0,NaN
8,251701,LEBLON BEACHFRONT VILLA APT.2,1319991,Jake,NaN,Vidigal,-22.99037,-43.23115,Entire home/apt,516,7,27,2019-11-13,0.21,11,365,0,NaN
9,251868,Great & comfy studio Copa!,1321287,Helena,NaN,Copacabana,-22.97920,-43.19010,Entire home/apt,120,4,85,2022-03-01,0.66,2,68,2,NaN
10,32539051,APART-HOTEL VIEIRA SOUTO 510,66213641,Lucia,NaN,Ipanema,-22.98737,-43.20967,Entire home/apt,1500,2,6,2022-03-07,0.15,1,364,3,NaN
11,25026,Beautiful Modern Decorated Studio in Copa,102840,Viviane,NaN,Copacabana,-22.97735,-43.19105,Entire home/apt,188,4,248,2022-03-15,1.69,1,133,10,NaN
12,14883302,Flat no melhor local de Ipanema,30383865,Rafael,NaN,Ipanema,-22.98745,-43.20388,Entire home/apt,950,3,4,2019-07-09,0.06,1,81,0,NaN
13,256323,Garden Studio - Home away from Home,1348172,Jennifer,NaN,Santa Teresa,-22.91742,-43.18330,Entire home/apt,169,3,203,2022-05-30,1.63,1,119,18,NaN
14,35764,COPACABANA SEA BREEZE - RIO - 25 X Superhost,153691,Patricia Miranda & Paulo,NaN,Copacabana,-22.98107,-43.19136,Entire home/apt,180,3,398,2022-06-18,2.79,1,53,37,NaN
15,257618,"Great Dbl Bed/Pvt Bath, Leme, 1 min from the Sea",1355685,Jorge,NaN,Leme,-22.96102,-43.16858,Private room,217,2,39,2018-12-17,0.31,2,241,0,NaN
16,262466,APTO BOTAFOGO - BEM LOCALIZADO,1377161,Ana Cristina,NaN,Botafogo,-22.95508,-43.18251,Entire home/apt,250,1,3,2016-01-05,0.03,1,89,0,NaN
17,921262,Apartamento cobertura Copacabana,4952896,Mauricio,NaN,Copacabana,-22.97165,-43.17551,Entire home/apt,170,3,262,2022-05-02,2.34,1,137,7,NaN
18,48305,Bright 6bed Penthouse Seconds from Beach,70933,Goitaca,NaN,Ipanema,-22.98591,-43.20302,Entire home/apt,1548,2,113,2022-06-08,0.82,8,280,32,NaN
19,14233530,4 SUÍTES - Frente para o mar,86536634,Thaisa,NaN,Barra da Tijuca,-23.01352,-43.32084,Entire home/apt,1600,2,9,2022-01-16,0.13,1,338,5,NaN

Com a função `info()` podemos apresentar diversos dados estruturais do DataFrame, tais como a quantidade de registros, os nomes das colunas, tipos de dados e uso de memória.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24881 entries, 0 to 24880
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              24881 non-null  int64
 1   name                            24860 non-null  object
 2   host_id                         24881 non-null  int64
 3   host_name                       24764 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   24881 non-null  object
 6   latitude                        24881 non-null  float64
 7   longitude                       24881 non-null  float64
 8   room_type                       24881 non-null  object
 9   price                           24881 non-null  int64
 10  minimum_nights                  24881 non-null  int64
 11  number_of_reviews               24881 non-null  int64
 12  last_review                     17213 non-null  object
 13  reviews_per_month               17213 non-null  float64
 14  calculated_host_listings_count  24881 non-null  int64
 15  availability_365                24881 non-null  int64
 16  number_of_reviews_ltm           24881 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(5), int64(8), object(5)
memory usage: 3.4+ MB

O objeto `shape` apresenta as dimensões do DataFrame indicando quantas linhas (registros) e quantos colunas (atributos) este tem:

In [ ]:
df.shape

(24881, 18)

Podemos ler uma coluna indicando o nome dela no DataFrame:

In [ ]:
df["host_name"]

0           Matthias
1            Andréia
2        Thiago Luiz
3             Sheila
4            Luciano
            ...
24876        Tatiane
24877      Elisabeth
24878        Claudia
24879        Claudia
24880        Jumpers
Name: host_name, Length: 24881, dtype: object

Podemos usar também a função `filter()` passando uma lista com o nome das colunas desejadas.

In [ ]:
df.filter(["host_name", "room_type", "price"])

         host_name        room_type  price
0         Matthias  Entire home/apt    350
1          Andréia     Private room    280
2      Thiago Luiz     Private room    107
3           Sheila     Private room   1000
4          Luciano     Private room   1850
...            ...              ...    ...
24876      Tatiane  Entire home/apt    251
24877    Elisabeth  Entire home/apt    440
24878      Claudia  Entire home/apt    380
24879      Claudia  Entire home/apt    300
24880      Jumpers  Entire home/apt    315

[24881 rows x 3 columns]

Podemos também apresentar os primeiros registros de um DataFrame com `head()`:

In [ ]:
df.head(7)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,17878,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",68997,Matthias,NaN,Copacabana,-22.96599,-43.17940,Entire home/apt,350,5,272,2022-04-23,1.87,1,311,8,NaN
1,556930647599893392,Venha passar uma pernoite em um veleiro na Urca!,198206849,Andréia,NaN,Urca,-22.94781,-43.16351,Private room,280,1,1,2022-02-19,0.25,1,365,1,NaN
2,1174007,100% Best View In Copa In Suite 2,3962758,Thiago Luiz,NaN,Copacabana,-22.97277,-43.17966,Private room,107,2,177,2022-06-07,1.69,6,357,29,NaN
3,8410797,Ipanema(Arpoador) 100mdo Mar/ Jan & Carnaval +Fev,42038091,Sheila,NaN,Ipanema,-22.98871,-43.19334,Private room,1000,3,1,2017-09-28,0.02,3,362,0,NaN
4,28053241,Navegar a Bordo de um Veleiro Francês no Rio!,193860988,Luciano,NaN,Urca,-22.95056,-43.17175,Private room,1850,2,0,NaN,NaN,1,180,0,NaN
5,249616,Flat at Barra Near by WINDSOR HOTEL,1307761,Malí,NaN,Barra da Tijuca,-23.01097,-43.32266,Entire home/apt,195,3,220,2020-04-20,1.73,2,24,0,NaN
6,249842,"Copacabana, central e perto da praia",1309444,Sonia,NaN,Copacabana,-22.96794,-43.18969,Private room,90,2,140,2022-04-08,1.12,3,6,14,NaN

Ou ainda os últimos registros de um DataFrame com `tail()`:

In [ ]:
df.tail(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
24878,650011310811912783,Apto em frente à praia com vista lateral mar,238604267,Claudia,NaN,Barra da Tijuca,-23.009351,-43.344853,Entire home/apt,380,1,0,NaN,NaN,12,90,0,NaN
24879,650020855611122186,Apto com vista deslumbrante na Barra,238604267,Claudia,NaN,Barra da Tijuca,-23.008220,-43.343700,Entire home/apt,300,2,0,NaN,NaN,12,89,0,NaN
24880,650025403378811576,Jumpinbed - Studio in Copacabana in front of t...,397106841,Jumpers,NaN,Copacabana,-22.976880,-43.189920,Entire home/apt,315,1,0,NaN,NaN,15,334,0,NaN

####Seleção dos dados

Em muitos casos teremos datasets com muitas colunas e nem sempre precisaremos utilizar todas elas. Carregar sempre todas as colunas pode ser oneroso em se tratando de processamento e até mesmo organização da nossa prática. Sendo assim, podemos determinar quais são as colunas que devem ser lidas e inseridas no DataFrame.

In [ ]:
dfn = pd.DataFrame(df, columns=["host_name", "name", "neighbourhood", "room_type", "minimum_nights", "price", "number_of_reviews", "reviews_per_month", "last_review"])
display(dfn)

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
1,Andréia,Venha passar uma pernoite em um veleiro na Urca!,Urca,Private room,1,280,1,0.25,2022-02-19
2,Thiago Luiz,100% Best View In Copa In Suite 2,Copacabana,Private room,2,107,177,1.69,2022-06-07
3,Sheila,Ipanema(Arpoador) 100mdo Mar/ Jan & Carnaval +Fev,Ipanema,Private room,3,1000,1,0.02,2017-09-28
4,Luciano,Navegar a Bordo de um Veleiro Francês no Rio!,Urca,Private room,2,1850,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
24876,Tatiane,Apartamento encantador no centro,Centro,Entire home/apt,1,251,0,NaN,NaN
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.00,2022-06-18
24878,Claudia,Apto em frente à praia com vista lateral mar,Barra da Tijuca,Entire home/apt,1,380,0,NaN,NaN
24879,Claudia,Apto com vista deslumbrante na Barra,Barra da Tijuca,Entire home/apt,2,300,0,NaN,NaN
24880,Jumpers,Jumpinbed - Studio in Copacabana in front of t...,Copacabana,Entire home/apt,1,315,0,NaN,NaN

Se necessitarmos criar um DataFrame com apenas algumas linhas, podemos usar a função `iloc` passando em uma lista os índices dos registros necessários. Podemos usar intervalos de valores como `iloc[10:30]` que irá retornar os registros dos índices 10 até 29. Se os registros tiverem índices em valores não numéricos, podemos usar `loc()`.

In [ ]:
df.iloc[[1, 2, 4, 10]]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
1,556930647599893392,Venha passar uma pernoite em um veleiro na Urca!,198206849,Andréia,NaN,Urca,-22.94781,-43.16351,Private room,280,1,1,2022-02-19,0.25,1,365,1,NaN
2,1174007,100% Best View In Copa In Suite 2,3962758,Thiago Luiz,NaN,Copacabana,-22.97277,-43.17966,Private room,107,2,177,2022-06-07,1.69,6,357,29,NaN
4,28053241,Navegar a Bordo de um Veleiro Francês no Rio!,193860988,Luciano,NaN,Urca,-22.95056,-43.17175,Private room,1850,2,0,NaN,NaN,1,180,0,NaN
10,32539051,APART-HOTEL VIEIRA SOUTO 510,66213641,Lucia,NaN,Ipanema,-22.98737,-43.20967,Entire home/apt,1500,2,6,2022-03-07,0.15,1,364,3,NaN

#### Operações em dados

Podemos fazer algumas operações em dados como agrupamentos e ordenações.

#### Agrupamentos

Usando a função `groupby()` podemos passar a(s) coluna(s) que queremos agrupar. No caso a seguir, estamos contando (função `count()`) os registros da coluna `name` agrupando pela coluna `neighbourhood`:

In [ ]:
dfn.groupby("neighbourhood")["name"].count()

neighbourhood
Abolição              4
Acari                 1
Alto da Boa Vista    36
Anchieta              2
Andaraí              39
                     ..
Vila Militar          2
Vila Valqueire       15
Vila da Penha         8
Zumbi                 1
Água Santa            3
Name: name, Length: 153, dtype: int64

Caso seja mais de um valor, temos que passar como listas:

In [ ]:
dfn.groupby(["neighbourhood", "room_type"])["name"].count()

neighbourhood      room_type
Abolição           Entire home/apt     3
                   Shared room         1
Acari              Entire home/apt     1
Alto da Boa Vista  Entire home/apt    28
                   Private room        7
                                      ..
Vila da Penha      Private room        5
                   Shared room         2
Zumbi              Entire home/apt     1
Água Santa         Entire home/apt     2
                   Private room        1
Name: name, Length: 371, dtype: int64

Se quiser exibir apenas os registros de um determinado grupo, pode-se usar a função `get_group()` passando por parâmetro o grupo desejado.

In [ ]:
dfn.groupby("neighbourhood").get_group("Copacabana")

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
2,Thiago Luiz,100% Best View In Copa In Suite 2,Copacabana,Private room,2,107,177,1.69,2022-06-07
6,Sonia,"Copacabana, central e perto da praia",Copacabana,Private room,2,90,140,1.12,2022-04-08
9,Helena,Great & comfy studio Copa!,Copacabana,Entire home/apt,4,120,85,0.66,2022-03-01
11,Viviane,Beautiful Modern Decorated Studio in Copa,Copacabana,Entire home/apt,4,188,248,1.69,2022-03-15
...,...,...,...,...,...,...,...,...,...
24833,Aretha,"Ótima suíte em Copacabana, a uma quadra da praia",Copacabana,Private room,3,186,12,0.23,2022-04-23
24835,Rafaele Bispo,Ocean front Copacabana post 5,Copacabana,Entire home/apt,7,230,4,0.19,2022-03-02
24858,Roberto,Apartamento vista mar em Copacabana.,Copacabana,Entire home/apt,3,170,0,NaN,NaN
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.00,2022-06-18
24880,Jumpers,Jumpinbed - Studio in Copacabana in front of t...,Copacabana,Entire home/apt,1,315,0,NaN,NaN

Temos alguns objetos implícitos com informações que podem ser úteis sobre o agrupamento. O objeto `groups` mostra um dicionário de dados completo com todos os índices para cada registro de agrupamento realizado.

In [ ]:
dfn.groupby("neighbourhood")["name"].groups

{'Abolição': [5226, 6540, 6863, 9166], 'Acari': [14023], 'Alto da Boa Vista': [383, 519, 1486, 2078, 2122, 3104, 5289, 6127, 6265, 6868, 6880, 6994, 8206, 8762, 10010, 10897, 12137, 12525, 12758, 13733, 14560, 15944, 16406, 17430, 17826, 19059, 19355, 21048, 22227, 22368, 22428, 22575, 22810, 23921, 24599, 24873], 'Anchieta': [6047, 14762], 'Andaraí': [869, 1018, 1626, 1689, 1887, 2228, 3611, 3789, 5909, 6784, 6816, 7070, 7144, 7259, 8122, 8427, 9900, 10180, 10181, 11812, 11963, 12031, 12076, 12107, 14042, 14921, 14954, 14983, 15929, 16228, 17678, 18183, 20490, 20573, 21429, 21512, 21682, 23169, 23244], 'Anil': [572, 1431, 2732, 3558, 4218, 4792, 5457, 5645, 6212, 6347, 6473, 6690, 7098, 7245, 7486, 8088, 10501, 11107, 11457, 12934, 13045, 13604, 13652, 14758, 15522, 17552, 17609, 18572, 18653, 19985, 20048, 20971, 21482, 21527, 21849, 22760, 23119, 23837, 23860, 23915, 24016, 24051, 24131, 24256, 24257, 24267, 24346, 24361, 24796], 'Bancários': [6029, 6033, 17534, 23398, 24439], 'Bangu': [912, 979, 6385, 17227, 17730, 18187, 18923, 19362, 19841, 21743, 21805], 'Barra da Tijuca': [5, 19, 20, 25, 29, 68, 79, 81, 83, 107, 117, 136, 160, 213, 237, 244, 268, 269, 323, 331, 352, 358, 372, 374, 376, 404, 444, 508, 534, 541, 553, 650, 659, 717, 723, 725, 734, 746, 769, 772, 820, 827, 836, 861, 875, 884, 887, 908, 926, 929, 948, 956, 959, 978, 1000, 1032, 1048, 1075, 1077, 1092, 1100, 1108, 1147, 1148, 1154, 1157, 1164, 1186, 1256, 1264, 1280, 1281, 1284, 1293, 1306, 1320, 1325, 1328, 1329, 1346, 1348, 1349, 1362, 1374, 1385, 1393, 1411, 1416, 1418, 1440, 1442, 1454, 1458, 1467, 1472, 1476, 1477, 1489, 1491, 1502, ...], 'Barra de Guaratiba': [648, 1097, 1113, 1548, 1549, 1877, 1900, 2156, 3707, 5504, 6619, 6907, 7037, 7069, 7412, 8139, 8563, 9141, 10022, 10318, 10521, 10673, 10812, 11211, 11237, 11278, 11290, 11291, 11292, 11371, 11372, 11691, 11874, 12095, 12317, 12503, 12792, 12825, 13408, 14534, 14542, 14982, 15034, 15051, 15307, 15384, 15660, 15678, 15948, 15980, 16112, 17144, 17279, 17316, 17403, 18431, 18514, 18573, 18714, 18748, 19650, 19791, 19952, 20142, 20205, 20229, 20269, 20271, 20389, 20543, 21047, 21092, 21534, 21694, 21741, 21750, 21864, 21994, 22030, 22129, 22130, 22301, 22427, 22451, 22511, 22512, 22515, 22602, 22721, 23192, 23317, 23584, 23745, 24704, 24781, 24866], 'Barros Filho': [2072], 'Benfica': [2313, 13837, 13900, 15078, 15573, 16326, 18589, 22855], 'Bento Ribeiro': [6793, 6902, 12212, 15515, 15674, 16255, 19451, 20721, 22901, 23518], 'Bonsucesso': [623, 4983, 11862, 11961, 12044, 12882, 12911, 12935, 13300, 13535, 13536, 13695, 14065, 14358, 14359, 14360, 14454, 14455, 14456, 14774, 21199], 'Botafogo': [16, 74, 86, 101, 144, 155, 169, 170, 181, 182, 208, 242, 289, 291, 312, 328, 380, 390, 393, 439, 450, 452, 461, 463, 517, 521, 522, 549, 550, 555, 557, 603, 618, 621, 656, 729, 768, 828, 845, 854, 872, 882, 924, 933, 944, 951, 992, 997, 999, 1023, 1039, 1052, 1053, 1072, 1080, 1087, 1104, 1117, 1131, 1169, 1198, 1221, 1226, 1237, 1243, 1314, 1317, 1334, 1343, 1357, 1405, 1463, 1464, 1479, 1511, 1513, 1552, 1565, 1577, 1606, 1609, 1623, 1687, 1702, 1713, 1722, 1731, 1779, 1817, 1845, 1923, 1954, 1962, 1991, 2026, 2050, 2099, 2128, 2139, 2147, ...], 'Brás de Pina': [3379, 4175, 5724, 6535, 7048, 7060, 7061, 9395, 10666, 11968, 12596, 12601, 12754, 13701, 14866, 15258, 15720, 18874, 23979], 'Cachambi': [1406, 1599, 1867, 1894, 3161, 3437, 6817, 6953, 7506, 8075, 9778, 10243, 10921, 13222, 14804, 15296, 15643, 15713, 17781, 18424, 20101, 23086], 'Cacuia': [9402, 9601, 9879, 10066, 10336, 10428, 12013, 24490], 'Caju': [30, 13120, 24145], 'Camorim': [1889, 2210, 3106, 3119, 3258, 3306, 3576, 3624, 3995, 4014, 4406, 4685, 4754, 4812, 4927, 4989, 5005, 5029, 5174, 5389, 5442, 5559, 5696, 5864, 5975, 5999, 6046, 6151, 6356, 6491, 6520, 6558, 6583, 6602, 6654, 6742, 6761, 6769, 6785, 6795, 6834, 6900, 6925, 7119, 7123, 7130, 7228, 7449, 7458, 7539, 7545, 7636, 7697, 8208, 8519, 8612, 8728, 9057, 9068, 9638, 9782, 9845, 9933, 9990, 9991, 10195, 10199, 10302, 10303, 10304, 10323, 10334, 10348, 10355, 10402, 10419, 10562, 10563, 10564, 10565, 10641, 10667, 10669, 10670, 10747, 10756, 10769, 10841, 10867, 10892, 10912, 10973, 10974, 11179, 11194, 11409, 11483, 11505, 11520, 11670, ...], 'Campinho': [1422, 4829, 5474, 5483, 7319, 8510, 8645, 15844, 17696], 'Campo Grande': [77, 88, 234, 2274, 2375, 2419, 3766, 4024, 4793, 4951, 5122, 6017, 6552, 6632, 6678, 7026, 7154, 7452, 10242, 11979, 12136, 12279, 12689, 13111, 13118, 13431, 13646, 13777, 14074, 14337, 14495, 14969, 15211, 15347, 15359, 15481, 15495, 15571, 15583, 15640, 15879, 15896, 15952, 15968, 15972, 16034, 16087, 16180, 16699, 16948, 17003, 17318, 17405, 17579, 17810, 18171, 18214, 18407, 18581, 18605, 18933, 18977, 19209, 19227, 19293, 19347, 19502, 19618, 21448, 21501, 21537, 21624, 21634, 21768, 22244, 22350, 22640, 23739, 23814, 23977, 24460, 24782, 24817], 'Cascadura': [10660, 15301], 'Catete': [747, 764, 852, 1197, 1276, 1685, 1813, 1837, 1858, 1970, 2126, 2144, 2194, 2335, 2352, 2817, 2896, 3017, 3080, 3142, 3494, 3583, 3640, 3745, 3862, 3946, 4102, 4294, 4312, 4371, 4449, 4462, 4567, 4578, 4802, 4881, 5033, 5103, 5228, 5263, 5294, 5691, 5979, 6344, 6378, 6510, 6733, 7258, 7509, 7714, 7741, 7804, 7848, 8091, 8101, 8349, 8398, 8417, 8435, 8485, 8792, 8856, 9137, 9192, 9281, 9532, 9560, 9703, 9780, 9862, 9989, 9996, 10170, 10407, 10422, 11038, 11056, 11147, 11216, 11231, 11353, 11373, 11442, 11461, 11479, 11635, 11711, 11715, 11746, 11880, 12134, 12521, 12568, 12909, 12941, 12980, 13482, 13547, 13642, 13897, ...], 'Catumbi': [6638, 10494, 12260, 16148, 18956, 19536, 19918, 23171, 24846], 'Cavalcanti': [1535], 'Centro': [54, 97, 187, 298, 322, 402, 506, 513, 532, 542, 581, 702, 807, 831, 832, 877, 878, 913, 925, 943, 952, 965, 1009, 1058, 1103, 1206, 1212, 1319, 1360, 1391, 1392, 1444, 1456, 1519, 1533, 1547, 1561, 1664, 1673, 1710, 1857, 1912, 1959, 1967, 1984, 2024, 2113, 2251, 2291, 2350, 2359, 2398, 2434, 2449, 2556, 2582, 2590, 2634, 2658, 2674, 2757, 2801, 2827, 2843, 2872, 2879, 2881, 2907, 2982, 2992, 3020, 3033, 3094, 3151, 3186, 3225, 3284, 3290, 3334, 3348, 3362, 3363, 3476, 3542, 3565, 3566, 3579, 3619, 3657, 3757, 3795, 3796, 3809, 3867, 3899, 3907, 3928, 4126, 4134, 4182, ...], 'Cidade Nova': [1255, 1450, 2636, 3342, 5325, 10244, 10852, 12014, 13402, 14325, 16210, 21504, 22985, 23212], 'Cidade Universitária': [10708, 16140], 'Cidade de Deus': [6097, 6608, 9020, 16838, 16915, 16947, 17892, 22913], 'Cocotá': [7971, 7972, 7973, 13612], 'Coelho Neto': [13071, 14947, 16511, 17842, 17933, 21289, 21508], 'Colégio': [20805, 21057], 'Complexo do Alemão': [8355, 9205], 'Copacabana': [0, 2, 6, 9, 11, 14, 17, 21, 22, 23, 27, 31, 32, 36, 43, 48, 62, 65, 69, 70, 71, 80, 84, 89, 90, 91, 92, 94, 95, 99, 100, 111, 116, 123, 125, 127, 130, 152, 153, 154, 159, 161, 162, 164, 165, 166, 167, 168, 174, 178, 179, 180, 184, 188, 189, 190, 191, 197, 199, 200, 204, 212, 214, 215, 217, 218, 221, 222, 225, 226, 227, 228, 240, 246, 247, 249, 253, 254, 257, 259, 260, 265, 266, 271, 272, 273, 274, 275, 276, 277, 286, 288, 292, 293, 294, 297, 301, 302, 304, 308, ...], 'Cordovil': [1847, 12321, 15471, 19614, 24761, 24847], 'Cosme Velho': [367, 431, 1543, 1688, 1692, 1693, 1788, 1969, 1971, 2214, 2472, 2765, 3288, 3486, 3510, 3805, 3948, 3975, 4213, 4618, 5081, 5680, 5836, 6131, 6737, 7146, 7305, 8318, 9169, 9432, 9747, 9760, 10183, 10257, 10339, 10344, 10498, 10499, 11122, 11405, 11657, 11689, 11761, 11776, 11924, 11993, 12878, 13164, 14076, 14749, 15371, 15624, 16165, 16393, 16572, 16588, 16946, 17843, 18062, 18959, 19035, 19330, 19424, 19818, 19849, 20076, 21211, 21245, 21421, 21422, 21424, 21425, 21426, 22017, 22044, 22213, 22745, 23365, 24529], 'Cosmos': [583, 4546, 8800, 13661, 14137, 16767, 18979, 19140, 22423, 23135], 'Curicica': [1013, 1159, 2575, 2577, 3144, 3381, 3659, 3890, 3972, 4041, 4195, 4196, 4344, 4440, 5172, 5488, 6203, 6617, 7145, 7374, 7376, 8445, 8551, 9945, 10041, 10044, 10363, 10548, 10575, 10580, 11029, 11309, 12294, 12296, 13352, 13373, 14024, 16392, 16706, 16826, 18148, 18648, 19179, 19303, 19436, 19583, 19584, 20196, 20208, 20599, 20725, 20941, 21973, 22356, 22708, 23096, 23269, 24182, 24194, 24253, 24287, 24518, 24714], 'Del Castilho': [2857, 4471, 13085, 13631, 14249, 16304, 22653, 24073], 'Deodoro': [16548], 'Encantado': [3103, 4897, 6039, 7708, 18031, 18593, 18594, 18792, 19487, 22514], 'Engenho Novo': [1153, 1473, 2199, 2200, 2339, 2603, 3935, 6923, 7243, 7318, 8429, 8834, 8974, 10142, 10412, 10423, 12229, 13545, 13738, 13776, 13811, 14940, 15161, 15889, 16014, 17188, 17347, 17581, 19949, 20991, 21001, 21139, 22762], 'Engenho da Rainha': [6573, 10161, 11973, 12623, 16041, 24703], 'Engenho de Dentro': [1682, 3331, 4721, 5278, 5309, 5342, 5454, 5592, 5619, 5911, 5931, 5932, 6316, 6349, 6555, 6565, 6803, 6873, 6876, 6895, 7526, 7560, 10475, 17472, 21885, 22207, 23534, 23574], 'Estácio': [303, 556, 915, 1305, 1820, 3544, 3548, 3855, 3908, 4443, 7397, 7531, 7860, 8144, 9575, 9713, 9937, 10477, 11243, 11343, 11518, 11770, 11971, 11991, 12041, 12498, 12706, 12841, 12842, 13286, 13500, 13513, 13528, 13737, 14428, 14611, 15026, 15102, 15127, 15168, 15405, 15554, 15784, 17817, 18021, 18251, 19201, 19349, 20368, 20530, 20596, 21134, 21135, 21917, 22025, 22215, 23535, 23954, 23956, 23960, 24281], 'Flamengo': [39, 82, 248, 256, 281, 320, 364, 540, 604, 606, 630, 818, 834, 971, 984, 1050, 1057, 1078, 1081, 1174, 1175, 1177, 1236, 1379, 1400, 1524, 1587, 1613, 1651, 1661, 1698, 1812, 1853, 1886, 1955, 1995, 2002, 2031, 2066, 2070, 2107, 2110, 2116, 2159, 2162, 2166, 2213, 2239, 2413, 2420, 2471, 2511, 2607, 2627, 2667, 2693, 2797, 2873, 2876, 3041, 3047, 3122, 3178, 3188, 3259, 3320, 3347, 3382, 3398, 3410, 3413, 3418, 3423, 3458, 3526, 3581, 3644, 3710, 3750, 3761, 3825, 3840, 3859, 3976, 3977, 4001, 4021, 4110, 4112, 4132, 4167, 4177, 4224, 4246, 4256, 4333, 4378, 4381, 4389, 4430, ...], 'Freguesia (Ilha)': [10200, 18064, 20017, 22032, 24863], 'Freguesia (Jacarepaguá)': [1553, 2008, 2068, 2195, 2304, 2397, 2515, 3364, 3676, 3788, 4098, 4475, 4554, 4619, 4745, 4799, 4816, 4879, 4928, 5311, 5317, 5586, 5606, 5735, 5800, 5811, 5845, 6267, 6309, 6343, 6367, 6380, 6469, 6554, 6655, 6679, 6685, 6696, 6713, 6757, 6758, 6796, 6885, 6972, 6988, 7082, 7162, 7199, 7212, 7217, 7218, 7225, 7310, 7347, 7351, 7407, 7485, 7548, 7792, 8487, 8574, 8725, 8743, 8801, 9355, 9489, 9499, 9613, 9720, 9834, 9859, 10097, 10124, 10517, 10599, 10601, 11172, 12385, 12416, 12805, 12966, 12987, 13619, 14068, 14512, 14719, 14801, 14934, 15097, 16004, 16529, 17086, 17208, 17457, 17772, 17952, 19010, 19690, 20544, 21083, ...], 'Gamboa': [599, 816, 5362, 6015, 10661, 10749, 12057, 15191, 15705, 15789, 16338, 16654, 17287, 17697, 19586, 21003, 22654, 23939], 'Gardênia Azul': [2082, 5007, 5694, 5837, 5980, 6012, 6585, 6770, 7400, 7415, 8397, 10557, 12881, 12972, 13277, 13621, 18313, 20217, 20560, 20602, 20615, 21921, 22799, 23856, 24236, 24441], 'Gericinó': [124, 4215], 'Glória': [110, 149, 278, 290, 370, 396, 412, 613, 671, 960, 974, 1044, 1068, 1140, 1208, 1211, 1381, 1404, 1494, 1514, 1518, 1555, 1603, 1746, 1883, 1944, 2009, 2034, 2096, 2268, 2358, 2400, 2502, 2520, 2727, 2829, 2839, 2867, 2944, 2945, 3015, 3419, 3469, 3473, 3516, 3738, 3883, 3934, 3965, 3974, 4005, 4086, 4105, 4169, 4217, 4289, 4317, 4405, 4628, 4632, 4919, 5234, 5396, 5830, 6381, 6400, 6664, 6681, 6710, 7200, 7283, 7349, 7622, 7718, 7742, 7771, 7825, 7910, 7977, 8062, 8099, 8136, 8354, 8356, 8556, 8568, 8615, 8881, 9328, 9382, 9409, 9452, 9480, 9546, 9648, 9682, 9796, 9825, 9865, 10074, ...], 'Grajaú': [1589, 1639, 1764, 1807, 1860, 2076, 2201, 3194, 3931, 4460, 4766, 5230, 5233, 5609, 5790, 5793, 6439, 6525, 6804, 7762, 7867, 8272, 10464, 11493, 11591, 12017, 12069, 12118, 12584, 12818, 12931, 13551, 13615, 14056, 14486, 14893, 16517, 18129, 18142, 18203, 18850, 19707, 19715, 21376, 21522, 22756, 22881, 23117, 24601, 24610], 'Grumari': [12111, 12592, 13126, 22288, 24842], 'Guadalupe': [6332, 7063, 7118, 7131, 7339, 16321, 24353, 24367], 'Guaratiba': [1445, 1937, 2418, 3171, 3927, 4125, 4144, 4341, 4759, 4794, 5397, 5441, 5729, 6007, 6048, 6780, 7269, 7600, 8044, 8240, 8367, 8413, 8471, 8911, 8967, 9436, 9500, 9681, 10371, 10386, 11052, 12507, 12869, 13134, 13525, 13921, 14273, 14800, 14824, 14944, 15160, 15279, 15441, 15799, 16091, 16092, 16093, 16094, 16158, 16324, 16377, 16515, 16660, 16981, 17106, 17634, 17746, 17820, 17838, 17947, 17970, 18136, 18156, 18371, 18402, 18455, 18614, 18882, 19166, 19871, 20135, 20164, 20344, 20429, 20483, 21144, 21145, 21658, 21788, 21986, 22013, 22200, 22731, 22742, 23088, 23533, 23746, 23782, 23930, 24347, 24446, 24548], 'Gávea': [55, 119, 353, 362, 385, 409, 427, 442, 443, 614, 903, 1015, 1190, 1286, 1290, 1302, 1308, 1377, 1637, 1674, 1708, 1729, 1796, 1819, 1865, 1893, 2133, 2306, 2466, 2539, 2553, 2557, 2608, 2825, 2898, 2906, 2916, 2926, 2927, 3051, 3095, 3162, 3199, 3242, 3375, 3395, 3553, 3681, 3811, 3900, 3971, 4076, 4281, 4543, 4764, 4808, 5026, 5108, 5144, 5160, 5255, 5387, 5406, 5473, 5636, 5808, 5812, 5816, 5888, 5939, 6016, 6064, 6239, 6361, 6421, 6717, 7582, 7585, 7690, 7812, 7957, 8021, 8057, 8082, 8904, 9038, 9054, 9306, 9310, 9315, 9754, 9783, 10072, 10376, 10478, 10811, 11089, 11632, 11718, 12083, ...], 'Higienópolis': [1554, 1737, 1966, 1974, 6231, 6644, 17736], 'Honório Gurgel': [12889, 13246, 18017], 'Humaitá': [145, 194, 251, 287, 309, 655, 694, 718, 809, 812, 1230, 1354, 1367, 1394, 1437, 1776, 1822, 1916, 2044, 2117, 2165, 2494, 2518, 2654, 2713, 2788, 2805, 2852, 3014, 3058, 3254, 3305, 3563, 3582, 3772, 4290, 4396, 4566, 4787, 4800, 5231, 5267, 5404, 5468, 5510, 5618, 5733, 5746, 5831, 6326, 6370, 6412, 6458, 6527, 6592, 6756, 6949, 6971, 7564, 7648, 7737, 7934, 8191, 8414, 8436, 8454, 8613, 8984, 9235, 9271, 9469, 9530, 9927, 10089, 10359, 10763, 11693, 11695, 11743, 11752, 11851, 12093, 12094, 12353, 12467, 12679, 13003, 13520, 13720, 13775, 14212, 14708, 14709, 14728, 14779, 14935, 15198, 15325, 15878, 16071, ...], 'Inhaúma': [2146, 3819, 4439, 7135, 7238, 7389, 7435, 12355, 18103, 24425], 'Inhoaíba': [3876, 5252, 8933, 15650, 16835, 19418, 20749, 22412], 'Ipanema': [3, 7, 10, 12, 18, 37, 38, 46, 57, 58, 66, 67, 73, 76, 112, 118, 128, 132, 140, 142, 146, 148, 150, 151, 157, 158, 173, 175, 176, 177, 185, 186, 192, 196, 198, 207, 216, 261, 262, 263, 264, 270, 279, 280, 284, 285, 296, 305, 306, 319, 332, 342, 349, 350, 351, 354, 356, 359, 363, 365, 366, 377, 378, 379, 384, 391, 392, 394, 397, 398, 399, 400, 403, 416, 418, 420, 422, 449, 458, 478, 479, 500, 501, 502, 503, 511, 516, 518, 527, 529, 530, 536, 537, 543, 544, 545, 546, 579, 580, 582, ...], 'Irajá': [3823, 5363, 6214, 7160, 7261, 8198, 8202, 8475, 9118, 9119, 9136, 11322, 11608, 12967, 13166, 13557, 15346, 18088, 18789, 19622, 20532, 22116, 23293, 23909], 'Itanhangá': [115, 586, 685, 991, 1629, 1754, 1763, 1914, 1927, 2020, 2456, 2859, 3112, 3187, 3631, 3895, 3933, 4410, 4545, 4560, 4626, 4648, 4655, 4795, 4891, 5076, 5721, 5802, 5905, 5949, 6096, 6220, 6376, 6384, 6549, 6553, 6862, 6906, 6979, 7129, 7179, 7316, 7490, 7723, 7902, 8087, 8238, 8269, 8542, 9078, 9079, 9334, 9610, 9646, 9803, 10570, 11522, 12035, 12036, 12154, 12163, 12457, 12698, 12761, 13064, 13076, 13385, 13512, 14764, 14836, 14943, 15297, 15340, 15504, 15547, 15661, 15865, 16500, 16794, 17073, 17082, 17386, 17455, 17687, 17689, 17748, 17862, 18023, 18043, 18272, 18749, 18799, 18802, 18856, 18990, 18991, 18992, 19345, 19580, 19599, ...], 'Jacarepaguá': [63, 147, 267, 535, 640, 700, 757, 765, 771, 774, 782, 783, 793, 860, 880, 885, 888, 1129, 1265, 1358, 1423, 1659, 1666, 1730, 1735, 1839, 1902, 2083, 2103, 2282, 2297, 2299, 2314, 2365, 2383, 2435, 2479, 2493, 2503, 2547, 2551, 2594, 2622, 2806, 2819, 2834, 3004, 3012, 3046, 3074, 3116, 3191, 3201, 3210, 3226, 3346, 3386, 3449, 3518, 3543, 3594, 3607, 3651, 3653, 3673, 3714, 3728, 3744, 3813, 3843, 3844, 3850, 3852, 3866, 3893, 3981, 3985, 4027, 4035, 4063, 4071, 4084, 4089, 4152, 4164, 4172, 4191, 4222, 4232, 4253, 4261, 4273, 4283, 4300, 4367, 4374, 4384, 4392, 4421, 4426, ...], 'Jacarezinho': [10351], 'Jacaré': [1939, 5262, 5728, 14152], 'Jardim América': [23892], 'Jardim Botânico': [201, 205, 295, 371, 421, 704, 844, 1046, 1121, 1193, 1250, 1260, 1288, 1521, 1551, 1570, 1593, 1740, 1786, 1863, 1871, 1892, 1947, 2004, 2097, 2163, 2187, 2317, 2318, 2369, 2370, 2403, 2431, 2461, 2623, 2930, 2950, 3006, 3030, 3477, 3740, 4293, 4307, 4350, 4402, 4423, 4432, 4478, 4867, 4869, 4907, 4943, 5120, 5195, 5331, 5368, 5408, 5558, 5634, 5646, 5668, 5856, 6435, 6645, 6847, 7299, 7615, 8187, 8285, 8286, 8391, 8404, 8457, 8622, 9026, 9179, 9193, 9210, 9274, 9324, 9361, 9745, 9898, 9950, 10060, 10070, 10091, 10434, 10502, 10701, 10776, 11053, 11156, 11182, 11272, 11446, 11557, 11719, 11933, 11952, ...], 'Jardim Carioca': [5782, 8161, 11551, 12700, 18523, 21025, 22118], 'Jardim Guanabara': [109, 1843, 3400, 6025, 6036, 6281, 6727, 6908, 6947, 7419, 7816, 7995, 9064, 9424, 9715, 9953, 10003, 10245, 10307, 10696, 10729, 10731, 11531, 11900, 12167, 12168, 12169, 12170, 13887, 14612, 14953, 15313, 15409, 15686, 15975, 16673, 16816, 17700, 17971, 17999, 18207, 18362, 18428, 18630, 19044, 19089, 19164, 19494, 19506, 20979, 21493, 21720, 23672, 24150, 24500], 'Jardim Sulacap': [469, 5169, 6916, 7891, 10037, 12646, 13197, 15982], 'Joá': [34, 172, 600, 900, 907, 1267, 1417, 1492, 2013, 2231, 2442, 2548, 3049, 3263, 3515, 3554, 3887, 3964, 4011, 4031, 4179, 4180, 4204, 4351, 4923, 6846, 6864, 7859, 8112, 8841, 8991, 10105, 10157, 10184, 10734, 10889, 11166, 11444, 11491, 11594, 11611, 11669, 11730, 11907, 12400, 12407, 12582, 12977, 12984, 13388, 13486, 13760, 13932, 14126, 14197, 14466, 14491, 15362, 15423, 15425, 15427, 15717, 15778, 16145, 16192, 16674, 16769, 16837, 16849, 17341, 17406, 17543, 17861, 17961, 18089, 18301, 18783, 18829, 19040, 19153, 19196, 19268, 19269, 19326, 19558, 19617, 19859, 20986, 21972, 22153, 22591, 22707, 22884, 22991, 23468, 23871, 24121, 24181, 24264, 24405, ...], 'Lagoa': [47, 75, 141, 250, 651, 657, 714, 897, 947, 990, 1165, 1204, 1292, 1303, 1318, 1359, 1419, 1462, 1490, 1598, 1617, 1621, 1622, 1650, 1669, 1696, 1749, 1830, 1896, 1940, 1952, 1989, 2015, 2071, 2174, 2651, 2680, 2723, 2831, 2889, 2890, 2935, 2975, 3384, 3438, 3451, 3457, 3459, 3495, 3626, 3746, 3846, 3863, 3877, 3925, 3961, 4050, 4079, 4119, 4166, 4292, 4326, 4353, 4404, 4450, 4576, 4600, 4601, 4771, 4788, 5032, 5133, 5222, 5379, 5439, 5461, 5534, 5554, 5595, 5662, 5758, 5771, 5781, 5969, 5995, 6019, 6159, 6207, 6254, 6310, 6369, 6833, 6836, 7221, 7275, 7292, 7302, 7402, 7519, 8165, ...], 'Laranjeiras': [72, 106, 126, 211, 252, 283, 307, 424, 440, 523, 563, 584, 608, 625, 639, 641, 711, 739, 745, 899, 918, 1085, 1090, 1094, 1170, 1223, 1368, 1395, 1396, 1397, 1426, 1432, 1441, 1469, 1542, 1640, 1672, 1743, 1755, 1885, 1921, 1926, 1957, 2109, 2164, 2202, 2232, 2259, 2271, 2312, 2430, 2447, 2451, 2454, 2455, 2483, 2521, 2612, 2615, 2687, 2717, 2744, 2747, 2818, 2882, 2883, 2937, 2956, 3152, 3203, 3227, 3340, 3355, 3356, 3455, 3629, 3814, 3896, 3905, 4127, 4138, 4176, 4202, 4231, 4272, 4301, 4334, 4399, 4400, 4413, 4489, 4550, 4608, 4633, 4663, 4664, 4693, 4710, 4737, 4768, ...], 'Leblon': [40, 49, 59, 98, 137, 138, 143, 206, 219, 223, 224, 282, 299, 338, 355, 429, 453, 468, 495, 505, 512, 514, 528, 531, 554, 559, 589, 598, 672, 676, 677, 686, 691, 695, 697, 701, 707, 715, 716, 719, 731, 751, 753, 763, 806, 821, 830, 876, 910, 940, 946, 969, 977, 981, 985, 1002, 1006, 1028, 1035, 1043, 1061, 1118, 1123, 1132, 1137, 1141, 1152, 1160, 1166, 1167, 1183, 1188, 1214, 1225, 1235, 1253, 1257, 1270, 1301, 1313, 1315, 1321, 1323, 1336, 1345, 1375, 1407, 1424, 1435, 1436, 1466, 1483, 1485, 1506, 1516, 1517, 1540, 1541, 1564, 1566, ...], 'Leme': [15, 93, 220, 382, 423, 432, 460, 520, 526, 538, 560, 570, 578, 679, 680, 687, 735, 893, 993, 995, 1082, 1162, 1163, 1199, 1274, 1363, 1402, 1482, 1571, 1647, 1667, 1750, 1

Já o objeto `indices` apresenta um dicionário com arrays de índices para cada valor gerado pelo agrupamento.

In [ ]:
dfn.groupby("neighbourhood")["name"].indices

{'Abolição': array([5226, 6540, 6863, 9166]),
 'Acari': array([14023]),
 'Alto da Boa Vista': array([  383,   519,  1486,  2078,  2122,  3104,  5289,  6127,  6265,
         6868,  6880,  6994,  8206,  8762, 10010, 10897, 12137, 12525,
        12758, 13733, 14560, 15944, 16406, 17430, 17826, 19059, 19355,
        21048, 22227, 22368, 22428, 22575, 22810, 23921, 24599, 24873]),
 'Anchieta': array([ 6047, 14762]),
 'Andaraí': array([  869,  1018,  1626,  1689,  1887,  2228,  3611,  3789,  5909,
         6784,  6816,  7070,  7144,  7259,  8122,  8427,  9900, 10180,
        10181, 11812, 11963, 12031, 12076, 12107, 14042, 14921, 14954,
        14983, 15929, 16228, 17678, 18183, 20490, 20573, 21429, 21512,
        21682, 23169, 23244]),
 'Anil': array([  572,  1431,  2732,  3558,  4218,  4792,  5457,  5645,  6212,
         6347,  6473,  6690,  7098,  7245,  7486,  8088, 10501, 11107,
        11457, 12934, 13045, 13604, 13652, 14758, 15522, 17552, 17609,
        18572, 18653, 19985, 20048, 20971, 21482, 21527, 21849, 22760,
        23119, 23837, 23860, 23915, 24016, 24051, 24131, 24256, 24257,
        24267, 24346, 24361, 24796]),
 'Bancários': array([ 6029,  6033, 17534, 23398, 24439]),
 'Bangu': array([  912,   979,  6385, 17227, 17730, 18187, 18923, 19362, 19841,
        21743, 21805]),
 'Barra da Tijuca': array([    5,    19,    20, ..., 24872, 24878, 24879]),
 'Barra de Guaratiba': array([  648,  1097,  1113,  1548,  1549,  1877,  1900,  2156,  3707,
         5504,  6619,  6907,  7037,  7069,  7412,  8139,  8563,  9141,
        10022, 10318, 10521, 10673, 10812, 11211, 11237, 11278, 11290,
        11291, 11292, 11371, 11372, 11691, 11874, 12095, 12317, 12503,
        12792, 12825, 13408, 14534, 14542, 14982, 15034, 15051, 15307,
        15384, 15660, 15678, 15948, 15980, 16112, 17144, 17279, 17316,
        17403, 18431, 18514, 18573, 18714, 18748, 19650, 19791, 19952,
        20142, 20205, 20229, 20269, 20271, 20389, 20543, 21047, 21092,
        21534, 21694, 21741, 21750, 21864, 21994, 22030, 22129, 22130,
        22301, 22427, 22451, 22511, 22512, 22515, 22602, 22721, 23192,
        23317, 23584, 23745, 24704, 24781, 24866]),
 'Barros Filho': array([2072]),
 'Benfica': array([ 2313, 13837, 13900, 15078, 15573, 16326, 18589, 22855]),
 'Bento Ribeiro': array([ 6793,  6902, 12212, 15515, 15674, 16255, 19451, 20721, 22901,
        23518]),
 'Bonsucesso': array([  623,  4983, 11862, 11961, 12044, 12882, 12911, 12935, 13300,
        13535, 13536, 13695, 14065, 14358, 14359, 14360, 14454, 14455,
        14456, 14774, 21199]),
 'Botafogo': array([   16,    74,    86, ..., 24804, 24870, 24874]),
 'Brás de Pina': array([ 3379,  4175,  5724,  6535,  7048,  7060,  7061,  9395, 10666,
        11968, 12596, 12601, 12754, 13701, 14866, 15258, 15720, 18874,
        23979]),
 'Cachambi': array([ 1406,  1599,  1867,  1894,  3161,  3437,  6817,  6953,  7506,
         8075,  9778, 10243, 10921, 13222, 14804, 15296, 15643, 15713,
        17781, 18424, 20101, 23086]),
 'Cacuia': array([ 9402,  9601,  9879, 10066, 10336, 10428, 12013, 24490]),
 'Caju': array([   30, 13120, 24145]),
 'Camorim': array([ 1889,  2210,  3106,  3119,  3258,  3306,  3576,  3624,  3995,
         4014,  4406,  4685,  4754,  4812,  4927,  4989,  5005,  5029,
         5174,  5389,  5442,  5559,  5696,  5864,  5975,  5999,  6046,
         6151,  6356,  6491,  6520,  6558,  6583,  6602,  6654,  6742,
         6761,  6769,  6785,  6795,  6834,  6900,  6925,  7119,  7123,
         7130,  7228,  7449,  7458,  7539,  7545,  7636,  7697,  8208,
         8519,  8612,  8728,  9057,  9068,  9638,  9782,  9845,  9933,
         9990,  9991, 10195, 10199, 10302, 10303, 10304, 10323, 10334,
        10348, 10355, 10402, 10419, 10562, 10563, 10564, 10565, 10641,
        10667, 10669, 10670, 10747, 10756, 10769, 10841, 10867, 10892,
        10912, 10973, 10974, 11179, 11194, 11409, 11483, 11505, 11520,
        11670, 11975, 11984, 12178, 12262, 12448, 12466, 12509, 12560,
        12672, 12835, 12837, 12846, 12849, 12850, 12855, 12915, 12923,
        13012, 13013, 13072, 13105, 13163, 13228, 13268, 13280, 13382,
        13432, 13709, 13730, 14214, 14291, 14321, 14347, 14461, 14587,
        14756, 15008, 15010, 15012, 15056, 15201, 15305, 15391, 15399,
        15400, 15462, 15463, 15558, 15670, 15671, 15689, 15694, 15728,
        15738, 15837, 15840, 15977, 16073, 16075, 16189, 16196, 16246,
        16259, 16263, 16313, 16337, 16399, 16400, 16591, 16666, 16704,
        16705, 16828, 16882, 17068, 17222, 17223, 17252, 17339, 17520,
        18126, 18178, 18330, 18335, 18338, 18500, 18503, 18518, 18598,
        18655, 18762, 18797, 18798, 18843, 18853, 19279, 19393, 19521,
        19990, 20087, 20108, 20534, 20561, 20568, 20584, 20587, 20945,
        21034, 21381, 21383, 21467, 21485, 21519, 21520, 21660, 21661,
        21715, 21815, 21959, 21976, 22001, 22089, 22623, 22642, 22649,
        22659, 22688, 22696, 22725, 22769, 22779, 22793, 22856, 22911,
        23008, 23014, 23372, 23524, 23851, 23937, 24063, 24120, 24126,
        24429, 24448, 24466, 24469, 24551, 24791, 24808]),
 'Campinho': array([ 1422,  4829,  5474,  5483,  7319,  8510,  8645, 15844, 17696]),
 'Campo Grande': array([   77,    88,   234,  2274,  2375,  2419,  3766,  4024,  4793,
         4951,  5122,  6017,  6552,  6632,  6678,  7026,  7154,  7452,
        10242, 11979, 12136, 12279, 12689, 13111, 13118, 13431, 13646,
        13777, 14074, 14337, 14495, 14969, 15211, 15347, 15359, 15481,
        15495, 15571, 15583, 15640, 15879, 15896, 15952, 15968, 15972,
        16034, 16087, 16180, 16699, 16948, 17003, 17318, 17405, 17579,
        17810, 18171, 18214, 18407, 18581, 18605, 18933, 18977, 19209,
        19227, 19293, 19347, 19502, 19618, 21448, 21501, 21537, 21624,
        21634, 21768, 22244, 22350, 22640, 23739, 23814, 23977, 24460,
        24782, 24817]),
 'Cascadura': array([10660, 15301]),
 'Catete': array([  747,   764,   852,  1197,  1276,  1685,  1813,  1837,  1858,
         1970,  2126,  2144,  2194,  2335,  2352,  2817,  2896,  3017,
         3080,  3142,  3494,  3583,  3640,  3745,  3862,  3946,  4102,
         4294,  4312,  4371,  4449,  4462,  4567,  4578,  4802,  4881,
         5033,  5103,  5228,  5263,  5294,  5691,  5979,  6344,  6378,
         6510,  6733,  7258,  7509,  7714,  7741,  7804,  7848,  8091,
         8101,  8349,  8398,  8417,  8435,  8485,  8792,  8856,  9137,
         9192,  9281,  9532,  9560,  9703,  9780,  9862,  9989,  9996,
        10170, 10407, 10422, 11038, 11056, 11147, 11216, 11231, 11353,
        11373, 11442, 11461, 11479, 11635, 11711, 11715, 11746, 11880,
        12134, 12521, 12568, 12909, 12941, 12980, 13482, 13547, 13642,
        13897, 14060, 14148, 14175, 14233, 14316, 14355, 14387, 14481,
        14552, 14592, 14689, 14795, 15049, 15090, 15119, 15213, 15241,
        15332, 15348, 15381, 15387, 15444, 15592, 16159, 16240, 16256,
        16563, 16628, 16635, 16698, 16774, 17015, 17069, 17299, 17305,
        17857, 18014, 18034, 18364, 18440, 18690, 18729, 18790, 18801,
        19095, 19184, 19491, 19591, 19623, 19877, 20074, 20128, 20155,
        20161, 20235, 20250, 20263, 20421, 20468, 20472, 20481, 20897,
        20934, 21079, 21171, 21488, 21566, 21816, 21890, 21927, 22068,
        22212, 22329, 22334, 22495, 22572, 22573, 22588, 22595, 22616,
        22671, 22736, 22775, 22791, 22906, 22915, 22961, 23074, 23581,
        23685, 23775, 24134, 24221, 24694]),
 'Catumbi': array([ 6638, 10494, 12260, 16148, 18956, 19536, 19918, 23171, 24846]),
 'Cavalcanti': array([1535]),
 'Centro': array([   54,    97,   187,   298,   322,   402,   506,   513,   532,
          542,   581,   702,   807,   831,   832,   877,   878,   913,
          925,   943,   952,   965,  1009,  1058,  1103,  1206,  1212,
         1319,  1360,  1391,  1392,  1444,  1456,  1519,  1533,  1547,
         1561,  1664,  1673,  1710,  1857,  1912,  1959,  1967,  1984,
         2024,  2113,  2251,  2291,  2350,  2359,  2398,  2434,  2449,
         2556,  2582,  2590,  2634,  2658,  2674,  2757,  2801,  2827,
         2843,  2872,  2879,  2881,  2907,  2982,  2992,  3020,  3033,
         3094,  3151,  3186,  3225,  3284,  3290,  3334,  3348,  3362,
         3363,  3476,  3542,  3565,  3566,  3579,  3619,  3657,  3757,
         3795,  3796,  3809,  3867,  3899,  3907,  3928,  4126,  4134,
         4182,  4257,  4295,  4299,  4315,  4332,  4409,  4412,  4442,
         4457,  4468,  4505,  4536,  4544,  4579,  4580,  4581,  4593,
         4610,  4616,  4642,  4650,  4683,  4718,  4726,  4820,  4929,
         4932,  4978,  5031,  5066,  5142,  5163,  5185,  5198,  5286,
         5296,  5422,  5630,  5663,  5664,  5698,  5825,  5863,  5907,
         5997,  6053,  6092,  6155,  6257,  6317,  6427,  6488,  6497,
         6529,  6614,  6622,  6667,  6670,  6689,  6732,  6841,  6845,
         6851,  6855,  6958,  7010,  7067,  7089,  7108,  7152,  7215,
         7255,  7334,  7337,  7352,  7358,  7369,  7379,  7446,  7703,
         7719,  7733,  7751,  7799,  7821,  7899,  7955,  7991,  7997,
         8008,  8063,  8180,  8184,  8204,  8226,  8261,  8280,  8308,
         8314,  8343,  8371,  8373,  8389,  8444,  8448,  8715,  8763,
         8768,  8786,  8825,  8861,  8873,  8874,  8909,  9000,  9077,
         9086,  9099,  9134,  9171,  9204,  9252,  9273,  9292,  9319,
         9416,  9448,  9459,  9463,  9523,  9568,  9579,  9582,  9583,
         9729,  9737,  9801,  9822,  9906,  9911,  9916,  9970, 10056,
        10165, 10238, 10256, 10313, 10358, 10370, 10474, 10508, 10552,
        10649, 10663, 10699, 10714, 10735, 10750, 10774, 10784, 10788,
        10819, 10874, 10893, 10894, 10913, 10936, 10996, 11062, 11072,
        11073, 11083, 11118, 11119, 11120, 11142, 11157, 11218, 11258,
        11312, 11359, 11362, 11410, 11441, 11450, 11503, 11552, 11633,
        11645, 11720, 11779, 11783, 11858, 11889, 11890, 11894, 11898,
        11953, 11972, 11981, 11982, 11988, 12000, 12002, 12039, 12052,
        12079, 12103, 12104, 12125, 12144, 12153, 12161, 12176, 12202,
        12315, 12410, 12444, 12465, 12468, 12492, 12538, 12539, 12540,
        12550, 12570, 12757, 12765, 12799, 12816, 12865, 12893, 12901,
        12929, 13056, 13117, 13128, 13172, 13181, 13253, 13262, 13263,
        13264, 13295, 13347, 13387, 13463, 13610, 13638, 13677, 13713,
        13717, 13732, 13739, 13785, 13832, 13836, 13843, 13863, 14036,
        14147, 14191, 14226, 14264, 14303, 14313, 14373, 14374, 14431,
        14532, 14567, 14572, 14614, 14688, 14698, 14701, 14710, 14743,
        14770, 14794, 14878, 14997, 15032, 15046, 15076, 15086, 15106,
        15111, 15122, 15134, 15147, 15181, 15217, 15218, 15275, 15310,
        15312, 15318, 15336, 15337, 15345, 15350, 15378, 15436, 15469,
        15539, 15541, 15542, 15548, 15553, 15602, 15617, 15618, 15641,
        15826, 15831, 15853, 15897, 15935, 15965, 15976, 16016, 16019,
        16033, 16037, 16058, 16078, 16114, 16160, 16198, 16206, 16219,
        16223, 16264, 16294, 16339, 16349, 16383, 16401, 16459, 16471,
        16519, 16552, 16564, 16583, 16584, 16613, 16679, 16680, 16681,
        16686, 16702, 16707, 16744, 16768, 16807, 16809, 16841, 16889,
        16901, 16917, 16937, 16939, 16966, 16982, 17025, 17071, 17100,
        17104, 17129, 17166, 17168, 17187, 17219, 17229, 17301, 17324,
        17371, 17444, 17545, 17548, 17549, 17550, 17614, 17706, 17741,
        17851, 17903, 17967, 17992, 18030, 18084, 18094, 18098, 18149,
        18216, 18265, 18299, 18310, 18385, 18411, 18432, 18513, 18550,
        18582, 18599, 18644, 18663, 18751, 18786, 18830, 18849, 18876,
        18884, 18968, 19006, 19021, 19119, 19150, 19223, 19283, 19301,
        19332, 19337, 19338, 19419, 19429, 19449, 19464, 19474, 19503,
        19508, 19509, 19523, 19538, 19542, 19576, 19589, 19651, 19748,
        19779, 19797, 19805, 19807, 19835, 19848, 19854, 19904, 19921,
        19941, 19973, 20011, 20075, 20094, 20145, 20173, 20241, 20256,
        20279, 20286, 20362, 20392, 20512, 20624, 20641, 20648, 20672,
        20683, 20744, 20752, 20761, 20799, 20903, 20904, 20933, 20960,
        20963, 20970, 21000, 21021, 21042, 21068, 21074, 21117, 21155,
        21176, 21191, 21222, 21225, 21264, 21266, 21288, 21292, 21293,
        21304, 21392, 21394, 21416, 21450, 21565, 21574, 21579, 21626,
        21707, 21744, 21789, 21807, 21825, 21854, 21868, 21881, 21929,
        21946, 22006, 22022, 22024, 22045, 22095, 22173, 22183, 22240,
        22243, 22467, 22494, 22546, 22576, 22594, 22600, 22605, 22674,
        22695, 22710, 22757, 22764, 22778, 22831, 22837, 22860, 22910,
        22962, 22993, 23025, 23182, 23198, 23199, 23221, 23222, 23271,
        23283, 23288, 23291, 23396, 23406, 23441, 23495, 23536, 23596,
        23610, 23664, 23698, 23705, 23741, 23743, 23777, 23827, 23932,
        23933, 23934, 24034, 24049, 24056, 24099, 24133, 24164, 24204,
        24231, 24276, 24332, 24379, 24467, 24496, 24584, 24591, 24593,
        24696, 24728, 24738, 24754, 24784, 24813, 24876]),
 'Cidade Nova': array([ 1255,  1450,  2636,  3342,  5325, 10244, 10852, 12014, 13402,
        14325, 16210, 21504, 22985, 23212]),
 'Cidade Universitária': array([10708, 16140]),
 'Cidade de Deus': array([ 6097,  6608,  9020, 16838, 16915, 16947, 17892, 22913]),
 'Cocotá': array([ 7971,  7972,  7973, 13612]),
 'Coelho Neto': array([13071, 14947, 16511, 17842, 17933, 21289, 21508]),
 'Colégio': array([20805, 21057]),
 'Complexo do Alemão': array([8355, 9205]),
 'Copacabana': array([    0,     2,     6, ..., 24858, 24877, 24880]),
 'Cordovil': array([ 1847, 12321, 15471, 19614, 24761, 24847]),
 'Cosme Velho': array([  367,   431,  1543,  1688,  1692,  1693,  1788,  1969,  1971,
         2214,  2472,  2765,  3288,  3486,  3510,  3805,  3948,  3975,
         4213,  4618,  5081,  5680,  5836,  6131,  6737,  7146,  7305,
         8318,  9169,  9432,  9747,  9760, 10183, 10257, 10339, 10344,
        10498, 10499, 11122, 11405, 11657, 11689, 11761, 11776, 11924,
        11993, 12878, 13164, 14076, 14749, 15371, 15624, 16165, 16393,
        16572, 16588, 16946, 17843, 18062, 18959, 19035, 19330, 19424,
        19818, 19849, 20076, 21211, 21245, 21421, 21422, 21424, 21425,
        21426, 22017, 22044, 22213, 22745, 23365, 24529]),
 'Cosmos': array([  583,  4546,  8800, 13661, 14137, 16767, 18979, 19140, 22423,
        23135]),
 'Curicica': array([ 1013,  1159,  2575,  2577,  3144,  3381,  3659,  3890,  3972,
         4041,  4195,  4196,  4344,  4440,  5172,  5488,  6203,  6617,
         7145,  7374,  7376,  8445,  8551,  9945, 10041, 10044, 10363,
        10548, 10575, 10580, 11029, 11309, 12294, 12296, 13352, 13373,
        14024, 16392, 16706, 16826, 18148, 18648, 19179, 19303, 19436,
        19583, 19584, 20196, 20208, 20599, 20725, 20941, 21973, 22356,
        22708, 23096, 23269, 24182, 24194, 24253, 24287, 24518, 24714]),
 'Del Castilho': array([ 2857,  4471, 13085, 13631, 14249, 16304, 22653, 24073]),
 'Deodoro': array([16548]),
 'Encantado': array([ 3103,  4897,  6039,  7708, 18031, 18593, 18594, 18792, 19487,
        22514]),
 'Engenho Novo': array([ 1153,  1473,  2199,  2200,  2339,  2603,  3935,  6923,  7243,
         7318,  8429,  8834,  8974, 10142, 10412, 10423, 12229, 13545,
        13738, 13776, 13811, 14940, 15161, 15889, 16014, 17188, 17347,
        17581, 19949, 20991, 21001, 21139, 22762]),
 'Engenho da Rainha': array([ 6573, 10161, 11973, 12623, 16041, 24703]),
 'Engenho de Dentro': array([ 1682,  3331,  4721,  5278,  5309,  5342,  5454,  5592,  5619,
         5911,  5931,  5932,  6316,  6349,  6555,  6565,  6803,  6873,
         6876,  6895,  7526,  7560, 10475, 17472, 21885, 22207, 23534,
        23574]),
 'Estácio': array([  303,   556,   915,  1305,  1820,  3544,  3548,  3855,  3908,
         4443,  7397,  7531,  7860,  8144,  9575,  9713,  9937, 10477,
        11243, 11343, 11518, 11770, 11971, 11991, 12041, 12498, 12706,
        12841, 12842, 13286, 13500, 13513, 13528, 13737, 14428, 14611,
        15026, 15102, 15127, 15168, 15405, 15554, 15784, 17817, 18021,
        18251, 19201, 19349, 20368, 20530, 20596, 21134, 21135, 21917,
        22025, 22215, 23535, 23954, 23956, 23960, 24281]),
 'Flamengo': array([   39,    82,   248,   256,   281,   320,   364,   540,   604,
          606,   630,   818,   834,   971,   984,  1050,  1057,  1078,
         1081,  1174,  1175,  1177,  1236,  1379,  1400,  1524,  1587,
         1613,  1651,  1661,  1698,  1812,  1853,  1886,  1955,  1995,
         2002,  2031,  2066,  2070,  2107,  2110,  2116,  2159,  2162,
         2166,  2213,  2239,  2413,  2420,  2471,  2511,  2607,  2627,
         2667,  2693,  2797,  2873,  2876,  3041,  3047,  3122,  3178,
         3188,  3259,  3320,  3347,  3382,  3398,  3410,  3413,  3418,
         3423,  3458,  3526,  3581,  3644,  3710,  3750,  3761,  3825,
         3840,  3859,  3976,  3977,  4001,  4021,  4110,  4112,  4132,
         4167,  4177,  4224,  4246,  4256,  4333,  4378,  4381,  4389,
         4430,  4437,  4644,  4652,  4751,  4765,  4773,  4835,  4873,
         4920,  5013,  5019,  5060,  5088,  5105,  5128,  5137,  5150,
         5167,  5173,  5223,  5238,  5242,  5351,  5352,  5393,  5430,
         5433,  5519,  5573,  5610,  5665,  5719,  5840,  5855,  5891,
         6009,  6055,  6068,  6104,  6149,  6199,  6255,  6319,  6324,
         6336,  6397,  6406,  6419,  6461,  6462,  6466,  6574,  6578,
         6598,  6623,  6631,  6775,  6781,  6913,  6921,  6932,  6950,
         6980,  7111,  7338,  7410,  7414,  7441,  7512,  7640,  7641,
         7652,  7676,  7679,  7738,  7749,  7764,  7879,  7882,  7903,
         8015,  8028,  8067,  8076,  8131,  8138,  8228,  8233,  8271,
         8288,  8297,  8333,  8351,  8534,  8536,  8559,  8570,  8698,
         8722,  8806,  8835,  8845,  8848,  8853,  8972,  9027,  9071,
         9090,  9143,  9148,  9203,  9211,  9231,  9278,  9380,  9418,
         9429,  9490,  9495,  9504,  9548,  9588,  9652,  9708,  9741,
         9755,  9817,  9824,  9841,  9843,  9885,  9894,  9895, 10000,
        10081, 10084, 10107, 10141, 10207, 10215, 10219, 10223, 10287,
        10299, 10321, 10408, 10418, 10615, 10676, 10677, 10692, 10967,
        11155, 11212, 11250, 11251, 11279, 11280, 11288, 11300, 11327,
        11345, 11346, 11347, 11355, 11356, 11422, 11430, 11484, 11486,
        11510, 11529, 11530, 11558, 11650, 11662, 11734, 11735, 11748,
        11765, 11831, 11871, 11903, 11911, 11932, 12055, 12088, 12120,
        12124, 12219, 12269, 12275, 12298, 12332, 12458, 12522, 12524,
        12561, 12573, 12699, 12720, 12756, 12788, 12789, 12875, 12894,
        12900, 12905, 13050, 13051, 13058, 13083, 13139, 13156, 13237,
        13238, 13240, 13294, 13321, 13465, 13473, 13504, 13508, 13588,
        13696, 13812, 13838, 13849, 13862, 13931, 14018, 14020, 14028,
        14057, 14111, 14142, 14183, 14259, 14282, 14297, 14307, 14319,
        14409, 14419, 14435, 14487, 14597, 14600, 14641, 14677, 14797,
        14803, 14811, 14814, 15083, 15091, 15124, 15188, 15189, 15207,
        15251, 15389, 15493, 15506, 15637, 15655, 15716, 15770, 15864,
        15971, 15988, 16010, 16012, 16161, 16221, 16236, 16330, 16359,
        16422, 16458, 16476, 16479, 16598, 16713, 16725, 16732, 16741,
        16791, 16814, 16859, 16934, 16943, 16984, 16991, 16998, 17045,
        17072, 17194, 17199, 17220, 17230, 17264, 17345, 17360, 17367,
        17398, 17421, 17511, 17541, 17580, 17685, 17785, 17854, 17856,
        17901, 17938, 17943, 18010, 18106, 18133, 18166, 18220, 18247,
        18283, 18318, 18337, 18351, 18370, 18483, 18618, 18689, 18694,
        18765, 18785, 18831, 18832, 18928, 18969, 19322, 19357, 19378,
        19379, 19395, 19433, 19527, 19601, 19676, 19799, 19856, 19908,
        20040, 20071, 20093, 20153, 20192, 20255, 20260, 20313, 20455,
        20469, 20498, 20781, 20861, 20892, 21030, 21091, 21169, 21192,
        21311, 21372, 21606, 21772, 21806, 21811, 21837, 21872, 21961,

Por fim, `ngroups` apresenta a quantidade de grupos criados pelo agrupamento.

In [ ]:
dfn.groupby("neighbourhood")["name"].ngroups

153

Em caso da necessidade de agregação de mais de uma operação no agrupamento, podemos usar a função `aggregate` indicando em uma lista quais operações devem ser realizadas:

In [ ]:
dfn.groupby("neighbourhood")["number_of_reviews"].aggregate(["count", "sum"])

                   count  sum
neighbourhood
Abolição               4    0
Acari                  1    0
Alto da Boa Vista     36  445
Anchieta               2    0
Andaraí               39  179
...                  ...  ...
Vila Militar           2   97
Vila Valqueire        15  162
Vila da Penha          8   20
Zumbi                  1    3
Água Santa             3    1

[153 rows x 2 columns]

#### Filtragem de dados

Podemos criar consultas de uma maneira muito semelhante ao que realizamos em consultas em bases de dados relacionais. A forma mais simples é criando o filtro dentro do DataFrame. No exemplo a seguir estamos selecionando todos os registros que o preço esteja entre 200 e 500 reais"

In [ ]:
dfn[ (dfn["price"] >= 200) & (dfn["price"] <= 500) ]

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
1,Andréia,Venha passar uma pernoite em um veleiro na Urca!,Urca,Private room,1,280,1,0.25,2022-02-19
15,Jorge,"Great Dbl Bed/Pvt Bath, Leme, 1 min from the Sea",Leme,Private room,2,217,39,0.31,2018-12-17
16,Ana Cristina,APTO BOTAFOGO - BEM LOCALIZADO,Botafogo,Entire home/apt,1,250,3,0.03,2016-01-05
20,Valerie & Alex,Duplex in BARRA w/private terrace,Barra da Tijuca,Entire home/apt,28,268,39,0.32,2022-05-24
...,...,...,...,...,...,...,...,...,...
24876,Tatiane,Apartamento encantador no centro,Centro,Entire home/apt,1,251,0,NaN,NaN
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.00,2022-06-18
24878,Claudia,Apto em frente à praia com vista lateral mar,Barra da Tijuca,Entire home/apt,1,380,0,NaN,NaN
24879,Claudia,Apto com vista deslumbrante na Barra,Barra da Tijuca,Entire home/apt,2,300,0,NaN,NaN
24880,Jumpers,Jumpinbed - Studio in Copacabana in front of t...,Copacabana,Entire home/apt,1,315,0,NaN,NaN

Aqui uma consulta com mais critérios e o uso de operadores relacionais e lógicos. Importante perceber que para AND devemos usar o símvolo `&` e para OR o símbolo `|`. Neste caso estamos filtrando os registros que tenham bairro "Copacabana" E com preço maior ou igual a 1000 E que a quantidade mínima de noites seja 4 OU que tenha mais do que 10 reviews.

In [ ]:
dfn[
    (dfn["neighbourhood"] == "Copacabana") &
    (dfn["price"] >= 1000) &
    ( ( dfn["minimum_nights"] == 4) | (dfn["number_of_reviews"] > 10) )
]

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
99,Renata,Beautiful Newly Renovated Studio in Copacabana !,Copacabana,Entire home/apt,4,2766,16,0.13,2018-02-20
168,Wolfgang,Penthouse Oceanview Copacab/Ipanema,Copacabana,Entire home/apt,5,1086,153,1.18,2022-06-03
179,Yann,Stunning penthouse with ocean view and panoram...,Copacabana,Entire home/apt,5,1110,71,0.54,2022-06-05
339,Gilles,Copacabana Penthouse Xavier - 4 rooms,Copacabana,Entire home/apt,1,1600,117,1.47,2022-06-06
388,Rubens,3 Bedrooms in the best point of Copacabana,Copacabana,Entire home/apt,3,1629,14,0.12,2020-01-02
...,...,...,...,...,...,...,...,...,...
20846,Gustavo,Apartamento Elegante & Design,Copacabana,Entire home/apt,4,1000,0,NaN,NaN
21014,Pineapples,CaviRio RD1003 | 2-bedroom apartment overlooki...,Copacabana,Entire home/apt,1,1041,12,1.99,2022-06-09
21098,Maria,Flat bem localizado entre Ipanema e Copacabana,Copacabana,Entire home/apt,4,1000,1,0.18,2022-01-02
21549,Luciano,IPA-COPA APARTAMENTO COMPLETO,Copacabana,Entire home/apt,4,10000,1,0.27,2022-03-02
24179,David,Apartamento de luxo com maravilhosa vista da p...,Copacabana,Entire home/apt,4,1150,1,1.00,2022-06-17

Podemos usar a função `isin()` para avaliar se um valor consta no DataFrame. O retorno será sempre verdadeiro ou falso. Ao inserimos como filtro do DataFrame teremos o retorno das linhas que atendem ao critério.

In [ ]:
dfn[dfn["host_name"].isin(["Claudia", "David"])]

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
27,David,Djalma Ocean View Studio with Amazing Views #100A,Copacabana,Entire home/apt,3,200,123,1.06,2022-06-14
60,David,Beach and Mountain beauty in Rio!,São Conrado,Private room,2,470,12,0.09,2016-08-14
308,Claudia,Amazing View Apt in Copacabana,Copacabana,Entire home/apt,2,455,326,2.77,2022-05-30
420,Claudia,few steps from Ipanema beach,Ipanema,Entire home/apt,3,600,21,0.32,2022-04-23
430,Claudia,Duplex penthouse near the beach,Copacabana,Entire home/apt,5,1000,3,0.04,2020-02-14
...,...,...,...,...,...,...,...,...,...
24547,Claudia,Copacabana Studio,Copacabana,Entire home/apt,7,190,0,NaN,NaN
24611,Claudia,Casa inteira na Ilha da Gigoia (Barra da Tijuca),Barra da Tijuca,Entire home/apt,3,273,0,NaN,NaN
24872,Claudia,Apto aconchegante na Barra,Barra da Tijuca,Entire home/apt,1,380,0,NaN,NaN
24878,Claudia,Apto em frente à praia com vista lateral mar,Barra da Tijuca,Entire home/apt,1,380,0,NaN,NaN
24879,Claudia,Apto com vista deslumbrante na Barra,Barra da Tijuca,Entire home/apt,2,300,0,NaN,NaN

Com a função `contains()` também podemos usar uma estratégia semelhante ao "LIKE" das consultas em SQL nos bancos de dados relacionais. Assim, buscaremos por um termo no conteúdo de determinada coluna do DataFrame. O atributo `case=False` faz com que seja ignorada a diferença entre maiúsculas e minúsculas.

In [ ]:
dfn[dfn["name"].str.contains("Piscina", case=False).fillna(False)]

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
148,Alexander,LUX RIO 06 - Flat Frente praia com piscina,Ipanema,Entire home/apt,3,621,19,1.10,2022-05-30
233,Ricardo,"Itaguaí Flat, garagem, piscina, Spa, academia...",Santa Cruz,Entire home/apt,1,250,0,NaN,NaN
236,Darke,"Apartamento 2 quartos, piscina, academia, Garagem",Vigário Geral,Entire home/apt,3,249,11,0.26,2022-01-02
788,Carlos Eduardo,"Casa 4 suítes,piscina,churrasqueira",Recreio dos Bandeirantes,Entire home/apt,3,1770,6,0.08,2022-01-30
1190,Guilherme,Casa especial com piscina,Gávea,Entire home/apt,2,4286,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
24785,Elizabeth,APTO GARDEN COM PISCINA EM CONDOMÍNIO DE LUXO,Recreio dos Bandeirantes,Entire home/apt,2,600,0,NaN,NaN
24796,Gustavo,Casa em condomínio com piscina e churrasqueira,Anil,Entire home/apt,2,880,0,NaN,NaN
24817,Eduardo,CASA AC FUTEBOL PISCINA SAUNA CHURR E PIZZA LENHA,Campo Grande,Entire home/apt,7,1000,0,NaN,NaN
24870,Cairo,"3Qtos c/ Vista Cinematográfica, Piscina, 400Mbps",Botafogo,Entire home/apt,4,855,0,NaN,NaN
24871,Georgiana,Pousada da Gigóia Barra da Tijuca. Piscina e c...,Barra da Tijuca,Private room,1,206,0,NaN,NaN

Para buscas simples com operadores relacionais e lógicos podemos usar também a função `query()`

In [ ]:
# dfn[ (dfn["neighbourhood"] == "Copacabana") & (dfn["price"] >=500) ]
dfn.query("neighbourhood == 'Copacabana' & price <= 500")

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
2,Thiago Luiz,100% Best View In Copa In Suite 2,Copacabana,Private room,2,107,177,1.69,2022-06-07
6,Sonia,"Copacabana, central e perto da praia",Copacabana,Private room,2,90,140,1.12,2022-04-08
9,Helena,Great & comfy studio Copa!,Copacabana,Entire home/apt,4,120,85,0.66,2022-03-01
11,Viviane,Beautiful Modern Decorated Studio in Copa,Copacabana,Entire home/apt,4,188,248,1.69,2022-03-15
...,...,...,...,...,...,...,...,...,...
24833,Aretha,"Ótima suíte em Copacabana, a uma quadra da praia",Copacabana,Private room,3,186,12,0.23,2022-04-23
24835,Rafaele Bispo,Ocean front Copacabana post 5,Copacabana,Entire home/apt,7,230,4,0.19,2022-03-02
24858,Roberto,Apartamento vista mar em Copacabana.,Copacabana,Entire home/apt,3,170,0,NaN,NaN
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.00,2022-06-18
24880,Jumpers,Jumpinbed - Studio in Copacabana in front of t...,Copacabana,Entire home/apt,1,315,0,NaN,NaN

In [ ]:
dfn.query("neighbourhood == 'Copacabana' & price <= 500")

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
2,Thiago Luiz,100% Best View In Copa In Suite 2,Copacabana,Private room,2,107,177,1.69,2022-06-07
6,Sonia,"Copacabana, central e perto da praia",Copacabana,Private room,2,90,140,1.12,2022-04-08
9,Helena,Great & comfy studio Copa!,Copacabana,Entire home/apt,4,120,85,0.66,2022-03-01
11,Viviane,Beautiful Modern Decorated Studio in Copa,Copacabana,Entire home/apt,4,188,248,1.69,2022-03-15
...,...,...,...,...,...,...,...,...,...
24833,Aretha,"Ótima suíte em Copacabana, a uma quadra da praia",Copacabana,Private room,3,186,12,0.23,2022-04-23
24835,Rafaele Bispo,Ocean front Copacabana post 5,Copacabana,Entire home/apt,7,230,4,0.19,2022-03-02
24858,Roberto,Apartamento vista mar em Copacabana.,Copacabana,Entire home/apt,3,170,0,NaN,NaN
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.00,2022-06-18
24880,Jumpers,Jumpinbed - Studio in Copacabana in front of t...,Copacabana,Entire home/apt,1,315,0,NaN,NaN

#### Ordenação de dados

Para ordenação dos dados, podemos usar a função `sort_values()` passando como parâmetro o rótulo da coluna que guiará a sequência.

In [ ]:
dfn.sort_values("price")

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
15468,Rio Design,Rio Design Hotel,Copacabana,Hotel room,1,0,0,NaN,NaN
16174,Selina,Selina Copacabana,Copacabana,Hotel room,1,0,211,11.36,2022-05-27
15469,Ra-Iz,Belga Hotel e Restaurante Ltda,Centro,Hotel room,1,0,0,NaN,NaN
15553,Américas Granada,Americas Granada Hotel,Centro,Hotel room,1,0,0,NaN,NaN
15589,Augusto'S,Augusto's Riocopa Hotel,Copacabana,Hotel room,1,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19608,Alexandre,Não está disponivel,Laranjeiras,Entire home/apt,7,102811,4,0.65,2022-02-14
13478,Loris,B&B Linda House - Double bedroom between Copac...,Copacabana,Private room,1,129068,0,NaN,NaN
17748,Thiago,Suítes e quartos no Itanhangá-temporada ou mensal,Itanhangá,Private room,2,130000,0,NaN,NaN
20117,Vitor,apartamento lindo em rua sem saída pertinho praia,Leme,Entire home/apt,1,316450,0,NaN,NaN
6460,Elizabeth,Temporary rentals for Brazilian Cup.,São Cristóvão,Shared room,6,591723,0,NaN,NaN

Por padrão os valores são apresentados em ordem crescente, assim se quiseremos que seja apresentado em ordem decrescente temos que usar o parâmetro `ascending=False`.

In [ ]:
dfn.sort_values("price", ascending=False)

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
6460,Elizabeth,Temporary rentals for Brazilian Cup.,São Cristóvão,Shared room,6,591723,0,NaN,NaN
20117,Vitor,apartamento lindo em rua sem saída pertinho praia,Leme,Entire home/apt,1,316450,0,NaN,NaN
17748,Thiago,Suítes e quartos no Itanhangá-temporada ou mensal,Itanhangá,Private room,2,130000,0,NaN,NaN
13478,Loris,B&B Linda House - Double bedroom between Copac...,Copacabana,Private room,1,129068,0,NaN,NaN
19608,Alexandre,Não está disponivel,Laranjeiras,Entire home/apt,7,102811,4,0.65,2022-02-14
...,...,...,...,...,...,...,...,...,...
16174,Selina,Selina Copacabana,Copacabana,Hotel room,1,0,211,11.36,2022-05-27
15589,Augusto'S,Augusto's Riocopa Hotel,Copacabana,Hotel room,1,0,0,NaN,NaN
15533,Américas Barra,Américas Barra Hotel & Eventos,Barra da Tijuca,Hotel room,1,0,0,NaN,NaN
15534,Américas,Américas Copacabana Hotel,Copacabana,Hotel room,2,0,0,NaN,NaN
15553,Américas Granada,Americas Granada Hotel,Centro,Hotel room,1,0,0,NaN,NaN

Também podemos fazer a ordenação pelos índices dos registros.

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
12629,Amaury,Ótimo apto em Copacabana ao lado do Metro,Copacabana,Entire home/apt,5,500,2,0.06,2022-01-06
4603,Marilda,Quarto para meninas ou amigas Para Réveillon 2020,Copacabana,Private room,2,500,0,NaN,NaN
17300,Caroline,Apartamento quadra da praia,Copacabana,Entire home/apt,3,500,0,NaN,NaN
22474,Vanessa,Apartamento amplo e encantador em Copacabana!,Copacabana,Entire home/apt,3,500,1,0.51,2022-04-24
2597,Vanessa,Charming loft between copacabana n ipanema beach,Copacabana,Entire home/apt,7,500,4,0.07,2019-03-05
...,...,...,...,...,...,...,...,...,...
23767,Pablo,Quarto compartilhado a 3 min da praia. posto 3.,Copacabana,Shared room,1,49,1,0.50,2022-04-23
15534,Américas,Américas Copacabana Hotel,Copacabana,Hotel room,2,0,0,NaN,NaN
15468,Rio Design,Rio Design Hotel,Copacabana,Hotel room,1,0,0,NaN,NaN
15589,Augusto'S,Augusto's Riocopa Hotel,Copacabana,Hotel room,1,0,0,NaN,NaN
16174,Selina,Selina Copacabana,Copacabana,Hotel room,1,0,211,11.36,2022-05-27

Podemos usar quantas colunas forem necessárias para estabelecer a ordenação, basta que seja indicado em formato de lista como parâmetro da função `sort_values()`.

In [ ]:
dfn.query("neighbourhood == 'Copacabana' & price <= 500").sort_values(["minimum_nights", "price"])

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
15468,Rio Design,Rio Design Hotel,Copacabana,Hotel room,1,0,0,NaN,NaN
15589,Augusto'S,Augusto's Riocopa Hotel,Copacabana,Hotel room,1,0,0,NaN,NaN
16174,Selina,Selina Copacabana,Copacabana,Hotel room,1,0,211,11.36,2022-05-27
23767,Pablo,Quarto compartilhado a 3 min da praia. posto 3.,Copacabana,Shared room,1,49,1,0.50,2022-04-23
12208,Jose Ricardo,RICARDO CASA PORTO SEGURO TUR COM WI-FI,Copacabana,Shared room,1,50,42,1.15,2020-03-21
...,...,...,...,...,...,...,...,...,...
17926,Christiane,"Apartamento aconchegante, a 50m da praia",Copacabana,Entire home/apt,365,200,0,NaN,NaN
2205,Melina,Modern & sunny apt in Copacabana,Copacabana,Entire home/apt,365,240,67,0.73,2017-01-30
9275,Márcia,Estúdio Copacabana Princesinha do Mar.,Copacabana,Entire home/apt,400,129,12,0.29,2022-03-18
4327,Eduardo,Quarto e Sala em Copacabana,Copacabana,Entire home/apt,500,350,0,NaN,NaN
14521,Romero,Copacabana quadra da praia!,Copacabana,Entire home/apt,1000,204,1,0.04,2020-02-29

#### Tratamento de dados

Para efetuar operações de tratamento de dados nos DataFrames a biblioteca Pandas apresenta algumas funções.

Por exemplo, a função `drop_duplicates()` que remove linhas com valores duplicados.

In [ ]:
dfn.drop_duplicates()

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
1,Andréia,Venha passar uma pernoite em um veleiro na Urca!,Urca,Private room,1,280,1,0.25,2022-02-19
2,Thiago Luiz,100% Best View In Copa In Suite 2,Copacabana,Private room,2,107,177,1.69,2022-06-07
3,Sheila,Ipanema(Arpoador) 100mdo Mar/ Jan & Carnaval +Fev,Ipanema,Private room,3,1000,1,0.02,2017-09-28
4,Luciano,Navegar a Bordo de um Veleiro Francês no Rio!,Urca,Private room,2,1850,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
24876,Tatiane,Apartamento encantador no centro,Centro,Entire home/apt,1,251,0,NaN,NaN
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.00,2022-06-18
24878,Claudia,Apto em frente à praia com vista lateral mar,Barra da Tijuca,Entire home/apt,1,380,0,NaN,NaN
24879,Claudia,Apto com vista deslumbrante na Barra,Barra da Tijuca,Entire home/apt,2,300,0,NaN,NaN
24880,Jumpers,Jumpinbed - Studio in Copacabana in front of t...,Copacabana,Entire home/apt,1,315,0,NaN,NaN

A função `isnull()` ou `isna()` que verifica se o registro contém valores fantantes (missing values).

In [ ]:
dfn.isnull()

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...
24876,False,False,False,False,False,False,False,True,True
24877,False,False,False,False,False,False,False,False,False
24878,False,False,False,False,False,False,False,True,True
24879,False,False,False,False,False,False,False,True,True
24880,False,False,False,False,False,False,False,True,True

Já a função `dropna()` remove os registros com valores faltantes. Essa operação é realizada em tempo de execução, por isso para registrar seus efeitos no DataFrame deve-se usar o parâmetro `inplace=True` ou então associar a um novo DataFrame.

In [ ]:
dflimpo = dfn.dropna()
display(dflimpo)

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
1,Andréia,Venha passar uma pernoite em um veleiro na Urca!,Urca,Private room,1,280,1,0.25,2022-02-19
2,Thiago Luiz,100% Best View In Copa In Suite 2,Copacabana,Private room,2,107,177,1.69,2022-06-07
3,Sheila,Ipanema(Arpoador) 100mdo Mar/ Jan & Carnaval +Fev,Ipanema,Private room,3,1000,1,0.02,2017-09-28
5,Malí,Flat at Barra Near by WINDSOR HOTEL,Barra da Tijuca,Entire home/apt,3,195,220,1.73,2020-04-20
...,...,...,...,...,...,...,...,...,...
24862,Neusa,Vidiga Ocean View,Vidigal,Entire home/apt,1,233,42,1.02,2022-05-25
24865,Maria,Apartamento frente mar para a praia de Ipanema...,Ipanema,Entire home/apt,1,1416,1,0.20,2022-01-22
24866,Francisco,Praia Barra de Guaratiba 4,Barra de Guaratiba,Entire home/apt,2,61,16,0.54,2022-05-28
24867,Fernando,Ipanema Residence with ocean view!,Ipanema,Entire home/apt,1,380,203,2.58,2022-05-30
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.00,2022-06-18

Pode também preencher os dados faltantes com o valor desejado usando a função `fillna()`:

In [ ]:
dfn = dfn.fillna("NULL")
display(dfn)

,host_name,name,neighbourhood,room_type,minimum_nights,price,number_of_reviews,reviews_per_month,last_review
0,Matthias,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",Copacabana,Entire home/apt,5,350,272,1.87,2022-04-23
1,Andréia,Venha passar uma pernoite em um veleiro na Urca!,Urca,Private room,1,280,1,0.25,2022-02-19
2,Thiago Luiz,100% Best View In Copa In Suite 2,Copacabana,Private room,2,107,177,1.69,2022-06-07
3,Sheila,Ipanema(Arpoador) 100mdo Mar/ Jan & Carnaval +Fev,Ipanema,Private room,3,1000,1,0.02,2017-09-28
4,Luciano,Navegar a Bordo de um Veleiro Francês no Rio!,Urca,Private room,2,1850,0,NULL,NULL
...,...,...,...,...,...,...,...,...,...
24876,Tatiane,Apartamento encantador no centro,Centro,Entire home/apt,1,251,0,NULL,NULL
24877,Elisabeth,Apartamento encantador em Copacabana,Copacabana,Entire home/apt,1,440,1,1.0,2022-06-18
24878,Claudia,Apto em frente à praia com vista lateral mar,Barra da Tijuca,Entire home/apt,1,380,0,NULL,NULL
24879,Claudia,Apto com vista deslumbrante na Barra,Barra da Tijuca,Entire home/apt,2,300,0,NULL,NULL
24880,Jumpers,Jumpinbed - Studio in Copacabana in front of t...,Copacabana,Entire home/apt,1,315,0,NULL,NULL

# 📚&nbsp;&nbsp;REFERÊNCIAS UTILIZADAS

[🔗](https://books.google.com.br/books?id=Oj5FDwAAQBAJ&printsec=frontcover&hl=pt-BR&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false) &nbsp;
MCKINNEY, Wes. **Python Para Análise de Dados: tratamento de dados com Pandas, NumPy e IPython**. Novatec Editora, 2018.

[🔗](https://pandas.pydata.org/docs/) &nbsp;
PANDAR OFFICIAL WEBSITE. **Pandas Documentation.** Version: 1.5.0, 2022.

#🔎&nbsp;&nbsp;CONTEÚDOS COMPLEMENTARES

#### **Links interessantes**

[🔗](https://www.geeksforgeeks.org/pandas-tutorial/) **GeeksforGeeks Pandas Tutorial:** um ótimo tutorial bastante detalhado e com exemplos de aplicação da biblioteca.

[🔗](https://www.kaggle.com/learn/pandas) **Kaggle Pandas:** tutorial da biblioteca Pandas feito pela Kaggle.